
Ñ"
errorcode.protoCmdbasetype.proto"Z
MessageErrorCode'
id (2.Cmd.EProtoId:ERROR_CODE_S
code (2.Cmd.EErrorCode*Ì!

EErrorCode
FAILEDÿÿ›¿
SUCCESS€€˜¿
DB_ERROR€˜¿

CONF_ERROR‚€˜¿
NAME_EXISTEDƒ€˜¿
MAX_ITEM_NUM„€˜¿
ROLE_LV_LIMIT…€˜¿
LV_NOT_ENOUGH†€˜¿
TOKEN_OVERDUE‡€˜¿
SERVER_IS_BUSYˆ€˜¿
SDK_OPT_ERROR‰€˜¿
CASH_NOT_ENOUGH€˜¿
GOLD_NOT_ENOUGH‘€˜¿
NAME_LEN_INVALID’€˜¿
CONTENT_HAVE_DIRTY“€˜¿
PROTO_INVALID”€˜¿
ITEM_NOT_FIND•€˜¿
VIP_NOT_SATISFY–€˜¿
BANK_OPEN_FAILED—€˜¿
BANK_CLOSED_FAILED˜€˜¿
TOKEN_NOT_FOUND™€˜¿
TOKEN_ERRORš€˜¿
IDLE_TIMEOUT›€˜¿
DAILY_REACH_LIMITœ€˜¿
IN_FORBID_TIME€˜¿
FULL_OF_ROLEž€˜¿
REWARD_HAVE_GOTŸ€˜¿
REWARD_TIME_LIMIT €˜¿
SOULDUST_NOT_ENOUGH¡€˜¿
ON_CREATING_ROLE¢€˜¿
MAX_ROLE_NUM_LIMIT£€˜¿
CREATE_SAME_ROLE_FORBID¤€˜¿
TIMES_REACH_LIMIT¥€˜¿
SYSTEM_NOT_OPEN¦€˜¿
USER_ID_ERROR‚˜¿
LOGIN_TOO_OFTEN‚‚˜¿
USER_RE_LOGINƒ‚˜¿
GATEWAY_NOT_FOUND„‚˜¿
SYSTEM_KICK_OFF…‚˜¿
DRESS_NOT_FIND„˜¿
DRESS_LV_MAX‚„˜¿
DRESSCONF_NOT_FINDƒ„˜¿ 
DRESSCONF_COSTITEM_ERROR„„˜¿
DRESS_ITEM_NOT_ENOUGH…„˜¿
STAR_NOT_ENOUGH†„˜¿
BP_NOT_ENOUGH‡„˜¿
CONSUME_NOT_ENOUGHˆ„˜¿
DUNGEON_NOT_ENOUGH‰„˜¿
ROLE_DATA_ERROR„˜¿
DRESS_EXP_FULL‘„˜¿
CLIMBTOWER_IS_NULL’„˜¿
SELECT_TOWER_TYPE_ERROR“„˜¿
HAVE_BEEN_SELECT”„˜¿
FIRST_TOWER_COPY_ERROR•„˜¿
TOWER_RESETTIMES_FULL–„˜¿
COST_CASH_IS_NULL—„˜¿
RESETTOWER_NOREWARDS˜„˜¿
HAVE_BEEN_RESET™„˜¿
RESETTIMES_NOT_ENOUGHTš„˜¿
CLIMBTOWER_REWARD_GET›„˜¿
NO_CLIMBTOWER_RWARDœ„˜¿#
CLIMBTOWER_REWARD_INDEX_ERR„˜¿"
CLIMBTOWER_REWARD_DROP_ERRž„˜¿
CLIMBTOWER_IS_TOPŸ„˜¿
CLIMBTOWER_REVIVE_NULL „˜¿
CLIMBTOWER_VIP_NOT_REW¡„˜¿
CLIMBTOWER_CASH_NOT_REW¢„˜¿
ACTION_ISNOT_EXIST£„˜¿
ACTION_ISCLOSE¤„˜¿
ACTION_COND_ISNOT_EXIST¥„˜¿
ACTION_COND_ISDONE¦„˜¿
ACTION_NOT_COMPLEATE§„˜¿
ACTION_NOT_REWARD_GET¨„˜¿!
ACTION_REWARDTIME_NOTARRI©„˜¿
ACTION_RANKREWARD_GETª„˜¿
ACTION_NOTIN_RANK«„˜¿
ACTION_SETGETREWARD_ERR¬„˜¿
ACTION_NO_SPECIAL­„˜¿
ACTION_EXCHANGE_NOT_OK®„˜¿
LEADEROFFLINE†˜¿
MEMBEROFFLINE‚†˜¿
COPYINVALIDƒ†˜¿
CREATECOPYFAIL„†˜¿
INICOPYFAIL…†˜¿
PLAYINFIGHT††˜¿
PLAYSTRNOTENOUGH‡†˜¿
CITYINVALIDˆ†˜¿
CITY_NOT_OPEN‰†˜¿
INVALIDŠ†˜¿
	BEINSCENE‹†˜¿
INCOPYŒ†˜¿
READYCOPYINVALID†˜¿
	NOTINCOPYŽ†˜¿
NOTHASBLADE†˜¿
COPYNOTACTIVE†˜¿
TELEIDFAILED‘†˜¿
REVIVEFAILED’†˜¿
REVIVECOINNOTENOUGH“†˜¿
REVIVETIMESNOTENOUGH”†˜¿
REVIVECASHNOTENOUGH•†˜¿
REFRESHSHOPCASHFAIL–†˜¿
REFRESHSHOPFAIL—†˜¿
SHOPSNOTEXIST˜†˜¿
SHOPSNOTENOUGH™†˜¿
BUYITEMRESNOTENOUGHš†˜¿
COPYIDINVALID›†˜¿
COPYNOTALLOWRUSHœ†˜¿
RUSHSTARNOTENOUGH†˜¿
SWEEPITEMNOTENOUGHž†˜¿
SWEEPCASHNOTENOUGHŸ†˜¿
SWEEPNUMSNOTENOUGH †˜¿
SWEEPPAYTYPEERROR¡†˜¿
COPYNUMNOTENOUGH¢†˜¿
BUYCOPYNUMTYPEERROR£†˜¿
COPYNUMNOTUSEOUT¤†˜¿
VIPCONFFAIL¥†˜¿
COPYNUMUSEOUT¦†˜¿
BUYCOPYNUMCASHNOTENOUGH§†˜¿
CHAPTERREWARD_STARERROR¨†˜¿
SWEEP_NOTUSECASH_VIP©†˜¿
SWEEP_NUMS_ERRORª†˜¿
SWEEP_NOTTEN_VIP«†˜¿
CHAPTER_REWARD_GET_DONE¬†˜¿!
CHAPTER_REWARD_TYPE_ERROR­†˜¿
CHAPTER_REWARD_VIP_FAIL®†˜¿
DB_OPERATOR_ERROR¯†˜¿
HAVE_NO_THIS_GIFT°†˜¿
DB_UPDATE_ERROR±†˜¿
GIFT_SOME_CONFIG_USED²†˜¿
DB_INSERT_ERROR³†˜¿
GIFT_GROUP_ERROR´†˜¿
GIFT_SOME_GROUP_USEDµ†˜¿
GIFT_LIMITNUM_ERROR¶†˜¿
GIFT_NOTIMES_TO_USE·†˜¿
GIFT_TYPE_ERROR¸†˜¿
GIFT_LEN_ERROR¹†˜¿
GIFT_REWARD_PARSEERRORº†˜¿
GIFT_STARTTIME_ERROR»†˜¿
GIFT_ENDTIME_EXPIRE¼†˜¿
GIFT_HAVE_USED½†˜¿
BATTLESQUARE_NOT_OPEN¾†˜¿
BATTLESQUARE_HAVE_BET¿†˜¿"
BATTLESQUARE_WIN_NOTENOUGHÀ†˜¿
BATTLESQUARE_WINRWD_GETÁ†˜¿
BATTLESQUARE_DROP_ERRORÂ†˜¿ 
BATTLESQUARE_BETCONF_ERRÃ†˜¿
BATTLESQUARE_VIP_NOTBETÄ†˜¿
STRONGREWARD_HAVE_GOTÅ†˜¿
STRONGREWARD_INDEX_ERRÆ†˜¿
STRONGREWARD_BP_NOTENOUÇ†˜¿
STRONGREWARD_DROP_ERRÈ†˜¿
BSCOIN_NOT_ENOUGHTÉ†˜¿
MAX_STRENGTH_LVˆ˜¿
ITEM_NOT_ENOUGH‚ˆ˜¿
MAX_BREAK_LVƒˆ˜¿
SKILL_POINT_NOT_ENOUGH„ˆ˜¿
MAX_SKILL_LV…ˆ˜¿
ILLEGAL_SKILL_ID†ˆ˜¿
FRONT_NODE_1ST‡ˆ˜¿
BUY_LIBERATION_LIMITˆˆ˜¿