
ÿ
masktype.protoCmd*ç
EMask
GACHA_OPENED
BLADE_OPENED
BLADE_STRENGTH_OPENED
ROLE_OPENED
SOUL_OPENED
SOUL_UPGRADE_OPENED
SHOP_OPENED
SOUL_ROOM_OPENED
GOLD_MACHINE_OPENED	
DAILY_REG_OPENED

HIGH_PVE_OPENED
ARENA_OPENED
CMD_PHONE_OPENED
LOCK_KONT_OPENED
SOUL_FIGHT_OPENED
LIBERATION_OPENED
TRAINING_OPENED
BOSS_OPENED
TOWER_OPENED
RANK_OPENED
SOULCORE_OPENED
BATTLESQUARE_OPENED
FREE_REWARD_OPENED