
«I
errorcode.protoCmdprototype.proto"\
MessageErrorCode)
id (2.Cmd.EMessageID:ERROR_CODE_S
code (2.Cmd.EErrorCode*£H

EErrorCode
FAILEDÿÿ›¿
SUCCESS€€˜¿
DB_ERROR€˜¿

CONF_ERROR‚€˜¿
NAME_EXISTEDƒ€˜¿
MAX_ITEM_NUM„€˜¿
USER_LV_LIMIT…€˜¿
LV_NOT_ENOUGH†€˜¿
SESSION_OVERDUE‡€˜¿
SERVER_IS_BUSYˆ€˜¿
SDK_OPT_ERROR‰€˜¿
CASH_NOT_ENOUGH€˜¿
GOLD_NOT_ENOUGH‘€˜¿
NAME_LEN_INVALID’€˜¿
CONTENT_HAVE_DIRTY“€˜¿
PROTO_INVALID”€˜¿
ITEM_NOT_FIND•€˜¿
VIP_NOT_SATISFY–€˜¿
BANK_OPEN_FAILED—€˜¿
BANK_CLOSED_FAILED˜€˜¿
TOKEN_NOT_FOUND™€˜¿
TOKEN_ERRORš€˜¿
IDLE_TIMEOUT›€˜¿
DAILY_REACH_LIMITœ€˜¿
IN_FORBID_TIME€˜¿
FULL_OF_USERž€˜¿
REWARD_HAVE_GOTŸ€˜¿
REWARD_TIME_LIMIT €˜¿
SOULDUST_NOT_ENOUGH¡€˜¿
ON_CREATING_USER¢€˜¿
MAX_USER_NUM_LIMIT£€˜¿
CREATE_SAME_USER_FORBID¤€˜¿
TIMES_REACH_LIMIT¥€˜¿
MODULE_NOT_OPEN¦€˜¿
CONFIG_VERSION_ERROR§€˜¿
COND_NOT_SATISFY¨€˜¿
TITLE_HAVE_ACTIVE©€˜¿
SEQUENCE_ERRORª€˜¿
FREETIMES_NOT_ENOUGH«€˜¿
PAYTIMES_NOT_ENOUGH¬€˜¿
USER_ID_ERROR‚˜¿
LOGIN_TOO_OFTEN‚‚˜¿
USER_RE_LOGINƒ‚˜¿
GATEWAY_NOT_FOUND„‚˜¿
SYSTEM_KICK_OFF…‚˜¿
DRESS_NOT_FIND„˜¿
DRESS_LV_MAX‚„˜¿
DRESSCONF_NOT_FINDƒ„˜¿ 
DRESSCONF_COSTITEM_ERROR„„˜¿
DRESS_ITEM_NOT_ENOUGH…„˜¿
STAR_NOT_ENOUGH†„˜¿
BP_NOT_ENOUGH‡„˜¿
CONSUME_NOT_ENOUGHˆ„˜¿
DUNGEON_NOT_ENOUGH‰„˜¿
USER_DATA_ERROR„˜¿
DRESS_EXP_FULL‘„˜¿
CLIMBTOWER_IS_NULL’„˜¿
SELECT_TOWER_TYPE_ERROR“„˜¿
HAVE_BEEN_SELECT”„˜¿
FIRST_TOWER_COPY_ERROR•„˜¿
TOWER_RESETTIMES_FULL–„˜¿
COST_CASH_IS_NULL—„˜¿
RESETTOWER_NOREWARDS˜„˜¿
HAVE_BEEN_RESET™„˜¿
RESETTIMES_NOT_ENOUGHTš„˜¿
CLIMBTOWER_REWARD_GET›„˜¿
NO_CLIMBTOWER_RWARDœ„˜¿#
CLIMBTOWER_REWARD_INDEX_ERR„˜¿"
CLIMBTOWER_REWARD_DROP_ERRž„˜¿
CLIMBTOWER_IS_TOPŸ„˜¿
CLIMBTOWER_REVIVE_NULL „˜¿
CLIMBTOWER_VIP_NOT_REW¡„˜¿
CLIMBTOWER_CASH_NOT_REW¢„˜¿
ACTION_ISNOT_EXIST£„˜¿
ACTION_ISCLOSE¤„˜¿
ACTION_COND_ISNOT_EXIST¥„˜¿
ACTION_COND_ISDONE¦„˜¿
ACTION_NOT_COMPLEATE§„˜¿
ACTION_NOT_REWARD_GET¨„˜¿!
ACTION_REWARDTIME_NOTARRI©„˜¿
ACTION_RANKREWARD_GETª„˜¿
ACTION_NOTIN_RANK«„˜¿
ACTION_SETGETREWARD_ERR¬„˜¿
ACTION_NO_SPECIAL­„˜¿
ACTION_EXCHANGE_NOT_OK®„˜¿
ACTIVE_DRESS_ITEM_NOT¯„˜¿
DRESS_HAS_ONE°„˜¿
LEADEROFFLINE†˜¿
MEMBEROFFLINE‚†˜¿
COPYINVALIDƒ†˜¿
CREATECOPYFAIL„†˜¿
INICOPYFAIL…†˜¿
PLAYINFIGHT††˜¿
PLAYSTRNOTENOUGH‡†˜¿
CITYINVALIDˆ†˜¿
CITY_NOT_OPEN‰†˜¿
INVALIDŠ†˜¿
	BEINSCENE‹†˜¿
INCOPYŒ†˜¿
READYCOPYINVALID†˜¿
	NOTINCOPYŽ†˜¿
NOTHASBLADE†˜¿
COPYNOTACTIVE†˜¿
TELEIDFAILED‘†˜¿
REVIVEFAILED’†˜¿
REVIVECOINNOTENOUGH“†˜¿
REVIVETIMESNOTENOUGH”†˜¿
REVIVECASHNOTENOUGH•†˜¿
REFRESHSHOPCASHFAIL–†˜¿
REFRESHSHOPFAIL—†˜¿
SHOPSNOTEXIST˜†˜¿
SHOPSNOTENOUGH™†˜¿
BUYITEMRESNOTENOUGHš†˜¿
COPYIDINVALID›†˜¿
COPYNOTALLOWRUSHœ†˜¿
RUSHSTARNOTENOUGH†˜¿
SWEEPITEMNOTENOUGHž†˜¿
SWEEPCASHNOTENOUGHŸ†˜¿
SWEEPNUMSNOTENOUGH †˜¿
SWEEPPAYTYPEERROR¡†˜¿
COPYNUMNOTENOUGH¢†˜¿
BUYCOPYNUMTYPEERROR£†˜¿
COPYNUMNOTUSEOUT¤†˜¿
VIPCONFFAIL¥†˜¿
COPYNUMUSEOUT¦†˜¿
BUYCOPYNUMCASHNOTENOUGH§†˜¿
CHAPTERREWARD_STARERROR¨†˜¿
SWEEP_NOTUSECASH_VIP©†˜¿
SWEEP_NUMS_ERRORª†˜¿
SWEEP_NOTTEN_VIP«†˜¿
CHAPTER_REWARD_GET_DONE¬†˜¿!
CHAPTER_REWARD_TYPE_ERROR­†˜¿
CHAPTER_REWARD_VIP_FAIL®†˜¿
DB_OPERATOR_ERROR¯†˜¿
HAVE_NO_THIS_GIFT°†˜¿
DB_UPDATE_ERROR±†˜¿
GIFT_SOME_CONFIG_USED²†˜¿
DB_INSERT_ERROR³†˜¿
GIFT_GROUP_ERROR´†˜¿
GIFT_SOME_GROUP_USEDµ†˜¿
GIFT_LIMITNUM_ERROR¶†˜¿
GIFT_NOTIMES_TO_USE·†˜¿
GIFT_TYPE_ERROR¸†˜¿
GIFT_LEN_ERROR¹†˜¿
GIFT_REWARD_PARSEERRORº†˜¿
GIFT_STARTTIME_ERROR»†˜¿
GIFT_ENDTIME_EXPIRE¼†˜¿
GIFT_HAVE_USED½†˜¿
BATTLESQUARE_NOT_OPEN¾†˜¿
BATTLESQUARE_HAVE_BET¿†˜¿"
BATTLESQUARE_WIN_NOTENOUGHÀ†˜¿
BATTLESQUARE_WINRWD_GETÁ†˜¿
BATTLESQUARE_DROP_ERRORÂ†˜¿ 
BATTLESQUARE_BETCONF_ERRÃ†˜¿
BATTLESQUARE_VIP_NOTBETÄ†˜¿
STRONGREWARD_HAVE_GOTÅ†˜¿
STRONGREWARD_INDEX_ERRÆ†˜¿
STRONGREWARD_BP_NOTENOUÇ†˜¿
STRONGREWARD_DROP_ERRÈ†˜¿
BSCOIN_NOT_ENOUGHTÉ†˜¿
UNION_SUBLEADER_FULLÊ†˜¿
UNION_ISNULLË†˜¿
UNION_POWER_NULLÌ†˜¿
UNION_NOTIN_UNIONÍ†˜¿
UNION_NOT_APPLYÎ†˜¿!
UNION_KICKPLAY_NOTINUNIONÏ†˜¿
UNION_NOT_LEADERÐ†˜¿ 
UNION_PLAYER_NOT_INUNIONÑ†˜¿
UNION_TITLE_ILLEGALÒ†˜¿
UNION_ASSIGN_SAME_TITLEÓ†˜¿"
UNION_CREATE_CASH_NOT_ENOUÔ†˜¿
UNION_NOT_KICKSELFÕ†˜¿
UNION_NOT_ASSIGNSELFÖ†˜¿
UNION_CONTENT_TOOLONG×†˜¿
UNION_SETPOINT_VIP_NOTØ†˜¿
UNION_SETPOINT_CASH_NOTÙ†˜¿
UNION_SKILLPOINT_NOTÚ†˜¿
UNION_SKILL_NOT_FINDÛ†˜¿
UNION_SKILLLV_FULLÜ†˜¿
UNION_IN_CDÝ†˜¿
UNION_CREATE_LV_NOÞ†˜¿
UNION_WASHSKILL_CASH_NOß†˜¿
UNION_PLAYER_FULLà†˜¿
UNION_HAVE_IN_UNIONá†˜¿
UNION_NAME_TOOLONGâ†˜¿
UNION_OPEN_NOTOPENã†˜¿
UNIONPOINT_NOT_ENOUGHä†˜¿
UNION_NAME_REPEATEDå†˜¿
UNION_LV_NOT_SATISFYæ†˜¿
UNION_BOSS_RUNNINGç†˜¿
UNION_LV_FULLè†˜¿
UNION_DONATE_TIMES_FULLé†˜¿
TOURNEY_NOT_PLAYERê†˜¿
TOURNEY_NOT_OPENë†˜¿
TOURNEY_DAILY_GETì†˜¿
TOURNEY_DAILYCOUNT_ERRí†˜¿
TOURNEY_DAILYCOUNT_NOTî†˜¿
TOURNEY_NOTOPEN_LEVELï†˜¿
TOURNEY_NOTOPEN_TIMEð†˜¿
TOURNEY_DAILYDROP_ERRñ†˜¿
CROSS_SVR_NOT_FOUNDò†˜¿
UNION_APPLY_HAS_SENDó†˜¿
UNION_APPLY_FULLô†˜¿
UNION_EXPITEM_NOTõ†˜¿
SHARE_COPY_REWDGETö†˜¿
SHARE_COPY_DROPERR÷†˜¿
MAX_STRENGTH_LVˆ˜¿
ITEM_NOT_ENOUGH‚ˆ˜¿
MAX_BREAK_LVƒˆ˜¿
SKILL_POINT_NOT_ENOUGH„ˆ˜¿
MAX_SKILL_LV…ˆ˜¿
ILLEGAL_SKILL_ID†ˆ˜¿
FRONT_NODE_1ST‡ˆ˜¿
BUY_LIBERATION_LIMITˆˆ˜¿
BANKAI_NOT_OPEN‰ˆ˜¿
BANKAI_LIBERATION_FIRSTŠˆ˜¿
BANKAI_MAX_LV‹ˆ˜¿
BANKAI_LV_NOT_ENOUGHŒˆ˜¿
BLADE_ALREADY_BANKAIˆ˜¿
ITEM_SELL_FORBIDŠ˜¿
ITEM_OUT_OF_DATE‚Š˜¿
ITEM_SELL_NUM_ERRƒŠ˜¿
ALREADY_IN_TEAMŒ˜¿
MAX_MEMBER_NUM‚Œ˜¿
MEMBER_NOT_FOUNDƒŒ˜¿
QUEST_INVALIDŽ˜¿
QUEST_STARTNPC_ERROR‚Ž˜¿
QUEST_ISDOINGƒŽ˜¿
QUEST_CANNOT_ACCEPT„Ž˜¿
QUEST_ACCEPT_FAILED…Ž˜¿
QUEST_NOT_DOING†Ž˜¿
QUEST_NOT_COMPLETE‡Ž˜¿
QUEST_ENDNPC_ERRORˆŽ˜¿
QUEST_REWARD_DROP_ERROR‰Ž˜¿!
QUEST_DAILYREWCOUNT_ERRORŠŽ˜¿
QUEST_DAILYREWARD_GET‹Ž˜¿
QUEST_DAILYREWCOUNT_NOTŒŽ˜¿ 
QUEST_DAILYREWDROP_ERRORŽ˜¿
MAIL_ALREADY_ACCEPTED˜¿
MAIL_NOT_FOUND‚˜¿
MAIL_HAVE_EXPIREDƒ˜¿
SOUL_NUM_LIMIT’˜¿
TYPE_INDEX_NOT_FIX‚’˜¿
SAME_INDEX_FORBIDƒ’˜¿
SOUL_INDEX_ILLEGAL„’˜¿
SAME_EQUIP_SOUL_FORBID…’˜¿
MERGE_NUM_LIMIT†’˜¿
FOUND_SAME_SOUL‡’˜¿
SOUL_NOT_FOUNDˆ’˜¿
SOUL_LV_MAX‰’˜¿
SOUL_GRADE_MAXŠ’˜¿ 
SOULFIGHT_REWARD_NOT_GET ’˜¿
SOULFIGHT_CARD_HVAE_GOT¡’˜¿
SOULFIGHT_INVALID_STAGE¢’˜¿
SOULFIGHT_NO_BLADE£’˜¿
SOULFIGHT_PLAYER_NULL¤’˜¿
SOULFIGHT_STAGE_ERROR¥’˜¿
SOULFIGHT_COPYID_ERROR¦’˜¿
SOULFIGHT_SP_NOT_ZERO§’˜¿
BATTLE_IS_OVER ˜¿
BATTLE_HAS_CALCULATE‚ ˜¿
BATTLE_OBJECT_NOTINƒ ˜¿!
BATTLE_CHANGESWORD_FAILED„ ˜¿ 
BATTLE_CROSSSCENE_FAILED… ˜¿
BATTLE_NOTHAVEBUFF† ˜¿
BATTLE_CDNOTCLEAR‡ ˜¿
BATTLE_NOTTHISSPELLˆ ˜¿
BATTLE_INSKILLCD‰ ˜¿$
BATTLE_EXPLODESWORD_NOTSKILLŠ ˜¿
BATTLE_CPNOTENOUGH‹ ˜¿
BATTLE_SKILLNOTFINDŒ ˜¿"
BATTLE_HASNOTBULLETINSPELL ˜¿
BATTLE_NOTTHISBULLETŽ ˜¿ 
BATTLE_PVE_CANFIGHTAGAIN ˜¿ 
BATTLE_NOTEND_FIGHTAGAIN ˜¿
BATTLE_SOULBAG_ISFULL‘ ˜¿
BATTLE_SPELL_NOSUMMON’ ˜¿"
BATTLE_CALLSUMMON_TYPE_ERR“ ˜¿'
BATTLE_RELEASEBULLET_TYPE_ERROR” ˜¿
BATTLE_BUFF_NOTEXIST• ˜¿
BATTLE_REVIVE_CD_NOT– ˜¿
BATTLE_NOT_CALCULATE— ˜¿
BATTLE_SEQUENCE_ERROR˜ ˜¿
BATTLE_BANKAIENERGY_NOT™ ˜¿
ARENA_IS_NOT_OPEN¢˜¿
ARENA_USER_ILLEGAL‚¢˜¿
ARENA_OUT_OF_FREE_TIMESƒ¢˜¿
ARENA_IN_CD„¢˜¿
ARENA_BUY_TIMES_LIMIT…¢˜¿
ARENA_HAVE_FREE_TIMES†¢˜¿
ARENA_HAVE_BUY_TIMES‡¢˜¿
ARENA_CHALLENGE_FORBIDˆ¢˜¿
ARENA_MATCHED_USER_1ST‰¢˜¿
ARENA_MATCHED_TIMEOUTŠ¢˜¿
TRAINING_CD_NOT_END¤˜¿
TRAINING_TIMES_LIMIT‚¤˜¿
TRAINING_TIME_INVALIDƒ¤˜¿
TRAINING_REQ_INVALID„¤˜¿ 
TRAINING_LV_NOT_STATISFY…¤˜¿
TRAINING_COPY_INVALID†¤˜¿
GACHA_REQ_INVALID¦˜¿
GACHA_GOLD_NOT_ENOUGH‚¦˜¿
GACHA_CASH_NOT_ENOUGHƒ¦˜¿
GACHA_CONF_INVALID„¦˜¿
SHOP_REQ_INVALID¨˜¿
GOODS_HAVE_BUY‚¨˜¿
BOSS_IS_NOT_OPENª˜¿
BOSS_OUT_OF_TIMES‚ª˜¿
BOSS_KENSEI_RUNINGƒª˜¿

BOSS_IN_CD„ª˜¿
BOSS_CURRENT_NOT_OPEN…ª˜¿
BOSS_USER_NUM_LIMIT†ª˜¿
BOSS_YAMMY_OVER‡ª˜¿
KEISEI_JOIN_TIMES_LIMITˆª˜¿
SLOT_ALREADY_OPEN¬˜¿
SLOT_NOT_OPEN‚¬˜¿
SCABBARD_INDEX_ERRORƒ¬˜¿
SCABBARD_SLOT_IN_CD„¬˜¿
SLOT_HAVE_BLADE…¬˜¿
SLOT_QUALITY_NOT_FIX†¬˜¿
SCABBARD_BLADE_IN_SLOT‡¬˜¿
SCABBARD_BLADE_IN_FIGHTˆ¬˜¿
RETRIEVE_HAVE_GOT®˜¿
RETRIEVE_TYPE_ERROR‚®˜¿
GUARD_HAS_OWNER°˜¿
GUARD_NOT_FOUND‚°˜¿
GUARD_IS_EMPTYƒ°˜¿
GUARD_IS_YOURSELFS„°˜¿
GUARD_IN_FIGHTING…°˜¿
GUARD_PROTECT_TIME†°˜¿
GUARD_TARGET_MISSED‡°˜¿