--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.herotype_pb')

HEROINFO = protobuf.Descriptor();
HEROINFO_THISID_FIELD = protobuf.FieldDescriptor();
HEROINFO_HEROID_FIELD = protobuf.FieldDescriptor();
HEROINFO_UID_FIELD = protobuf.FieldDescriptor();
HEROINFO_LEVEL_FIELD = protobuf.FieldDescriptor();
HEROINFO_QUALITY_FIELD = protobuf.FieldDescriptor();
HEROINFO_STAR_FIELD = protobuf.FieldDescriptor();

HEROINFO_THISID_FIELD.name = "thisid"
HEROINFO_THISID_FIELD.full_name = ".Cmd.HeroInfo.thisid"
HEROINFO_THISID_FIELD.number = 1
HEROINFO_THISID_FIELD.index = 0
HEROINFO_THISID_FIELD.label = 2
HEROINFO_THISID_FIELD.has_default_value = false
HEROINFO_THISID_FIELD.default_value = 0
HEROINFO_THISID_FIELD.type = 4
HEROINFO_THISID_FIELD.cpp_type = 4

HEROINFO_HEROID_FIELD.name = "heroid"
HEROINFO_HEROID_FIELD.full_name = ".Cmd.HeroInfo.heroid"
HEROINFO_HEROID_FIELD.number = 2
HEROINFO_HEROID_FIELD.index = 1
HEROINFO_HEROID_FIELD.label = 2
HEROINFO_HEROID_FIELD.has_default_value = false
HEROINFO_HEROID_FIELD.default_value = 0
HEROINFO_HEROID_FIELD.type = 13
HEROINFO_HEROID_FIELD.cpp_type = 3

HEROINFO_UID_FIELD.name = "uid"
HEROINFO_UID_FIELD.full_name = ".Cmd.HeroInfo.uid"
HEROINFO_UID_FIELD.number = 3
HEROINFO_UID_FIELD.index = 2
HEROINFO_UID_FIELD.label = 2
HEROINFO_UID_FIELD.has_default_value = false
HEROINFO_UID_FIELD.default_value = 0
HEROINFO_UID_FIELD.type = 4
HEROINFO_UID_FIELD.cpp_type = 4

HEROINFO_LEVEL_FIELD.name = "level"
HEROINFO_LEVEL_FIELD.full_name = ".Cmd.HeroInfo.level"
HEROINFO_LEVEL_FIELD.number = 4
HEROINFO_LEVEL_FIELD.index = 3
HEROINFO_LEVEL_FIELD.label = 2
HEROINFO_LEVEL_FIELD.has_default_value = false
HEROINFO_LEVEL_FIELD.default_value = 0
HEROINFO_LEVEL_FIELD.type = 13
HEROINFO_LEVEL_FIELD.cpp_type = 3

HEROINFO_QUALITY_FIELD.name = "quality"
HEROINFO_QUALITY_FIELD.full_name = ".Cmd.HeroInfo.quality"
HEROINFO_QUALITY_FIELD.number = 5
HEROINFO_QUALITY_FIELD.index = 4
HEROINFO_QUALITY_FIELD.label = 2
HEROINFO_QUALITY_FIELD.has_default_value = false
HEROINFO_QUALITY_FIELD.default_value = 0
HEROINFO_QUALITY_FIELD.type = 13
HEROINFO_QUALITY_FIELD.cpp_type = 3

HEROINFO_STAR_FIELD.name = "star"
HEROINFO_STAR_FIELD.full_name = ".Cmd.HeroInfo.star"
HEROINFO_STAR_FIELD.number = 6
HEROINFO_STAR_FIELD.index = 5
HEROINFO_STAR_FIELD.label = 2
HEROINFO_STAR_FIELD.has_default_value = false
HEROINFO_STAR_FIELD.default_value = 0
HEROINFO_STAR_FIELD.type = 13
HEROINFO_STAR_FIELD.cpp_type = 3

HEROINFO.name = "HeroInfo"
HEROINFO.full_name = ".Cmd.HeroInfo"
HEROINFO.nested_types = {}
HEROINFO.enum_types = {}
HEROINFO.fields = {HEROINFO_THISID_FIELD, HEROINFO_HEROID_FIELD, HEROINFO_UID_FIELD, HEROINFO_LEVEL_FIELD, HEROINFO_QUALITY_FIELD, HEROINFO_STAR_FIELD}
HEROINFO.is_extendable = false
HEROINFO.extensions = {}

HeroInfo = protobuf.Message(HEROINFO)

