--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local fighttype_pb = require("Protol.fighttype_pb")
module('Protol.pvptype_pb')

PVPHEROINFO = protobuf.Descriptor();
PVPHEROINFO_THISID_FIELD = protobuf.FieldDescriptor();
PVPHEROINFO_HEROID_FIELD = protobuf.FieldDescriptor();
PVPHEROINFO_INITHP_FIELD = protobuf.FieldDescriptor();
PVPHEROINFO_INIT_POS_FIELD = protobuf.FieldDescriptor();
PVPHEROINFO_DIRECT_FIELD = protobuf.FieldDescriptor();
FIGHTERINFO = protobuf.Descriptor();
FIGHTERINFO_UID_FIELD = protobuf.FieldDescriptor();
FIGHTERINFO_HEROS_FIELD = protobuf.FieldDescriptor();

PVPHEROINFO_THISID_FIELD.name = "thisid"
PVPHEROINFO_THISID_FIELD.full_name = ".Cmd.PvpHeroInfo.thisid"
PVPHEROINFO_THISID_FIELD.number = 1
PVPHEROINFO_THISID_FIELD.index = 0
PVPHEROINFO_THISID_FIELD.label = 1
PVPHEROINFO_THISID_FIELD.has_default_value = false
PVPHEROINFO_THISID_FIELD.default_value = 0
PVPHEROINFO_THISID_FIELD.type = 4
PVPHEROINFO_THISID_FIELD.cpp_type = 4

PVPHEROINFO_HEROID_FIELD.name = "heroid"
PVPHEROINFO_HEROID_FIELD.full_name = ".Cmd.PvpHeroInfo.heroid"
PVPHEROINFO_HEROID_FIELD.number = 2
PVPHEROINFO_HEROID_FIELD.index = 1
PVPHEROINFO_HEROID_FIELD.label = 1
PVPHEROINFO_HEROID_FIELD.has_default_value = false
PVPHEROINFO_HEROID_FIELD.default_value = 0
PVPHEROINFO_HEROID_FIELD.type = 13
PVPHEROINFO_HEROID_FIELD.cpp_type = 3

PVPHEROINFO_INITHP_FIELD.name = "inithp"
PVPHEROINFO_INITHP_FIELD.full_name = ".Cmd.PvpHeroInfo.inithp"
PVPHEROINFO_INITHP_FIELD.number = 3
PVPHEROINFO_INITHP_FIELD.index = 2
PVPHEROINFO_INITHP_FIELD.label = 1
PVPHEROINFO_INITHP_FIELD.has_default_value = false
PVPHEROINFO_INITHP_FIELD.default_value = 0
PVPHEROINFO_INITHP_FIELD.type = 13
PVPHEROINFO_INITHP_FIELD.cpp_type = 3

PVPHEROINFO_INIT_POS_FIELD.name = "init_pos"
PVPHEROINFO_INIT_POS_FIELD.full_name = ".Cmd.PvpHeroInfo.init_pos"
PVPHEROINFO_INIT_POS_FIELD.number = 4
PVPHEROINFO_INIT_POS_FIELD.index = 3
PVPHEROINFO_INIT_POS_FIELD.label = 1
PVPHEROINFO_INIT_POS_FIELD.has_default_value = false
PVPHEROINFO_INIT_POS_FIELD.default_value = nil
PVPHEROINFO_INIT_POS_FIELD.message_type = fighttype_pb.VECTOR_FLOAT
PVPHEROINFO_INIT_POS_FIELD.type = 11
PVPHEROINFO_INIT_POS_FIELD.cpp_type = 10

PVPHEROINFO_DIRECT_FIELD.name = "direct"
PVPHEROINFO_DIRECT_FIELD.full_name = ".Cmd.PvpHeroInfo.direct"
PVPHEROINFO_DIRECT_FIELD.number = 5
PVPHEROINFO_DIRECT_FIELD.index = 4
PVPHEROINFO_DIRECT_FIELD.label = 1
PVPHEROINFO_DIRECT_FIELD.has_default_value = false
PVPHEROINFO_DIRECT_FIELD.default_value = nil
PVPHEROINFO_DIRECT_FIELD.message_type = fighttype_pb.VECTOR_FLOAT
PVPHEROINFO_DIRECT_FIELD.type = 11
PVPHEROINFO_DIRECT_FIELD.cpp_type = 10

PVPHEROINFO.name = "PvpHeroInfo"
PVPHEROINFO.full_name = ".Cmd.PvpHeroInfo"
PVPHEROINFO.nested_types = {}
PVPHEROINFO.enum_types = {}
PVPHEROINFO.fields = {PVPHEROINFO_THISID_FIELD, PVPHEROINFO_HEROID_FIELD, PVPHEROINFO_INITHP_FIELD, PVPHEROINFO_INIT_POS_FIELD, PVPHEROINFO_DIRECT_FIELD}
PVPHEROINFO.is_extendable = false
PVPHEROINFO.extensions = {}
FIGHTERINFO_UID_FIELD.name = "uid"
FIGHTERINFO_UID_FIELD.full_name = ".Cmd.FighterInfo.uid"
FIGHTERINFO_UID_FIELD.number = 1
FIGHTERINFO_UID_FIELD.index = 0
FIGHTERINFO_UID_FIELD.label = 1
FIGHTERINFO_UID_FIELD.has_default_value = false
FIGHTERINFO_UID_FIELD.default_value = 0
FIGHTERINFO_UID_FIELD.type = 4
FIGHTERINFO_UID_FIELD.cpp_type = 4

FIGHTERINFO_HEROS_FIELD.name = "heros"
FIGHTERINFO_HEROS_FIELD.full_name = ".Cmd.FighterInfo.heros"
FIGHTERINFO_HEROS_FIELD.number = 2
FIGHTERINFO_HEROS_FIELD.index = 1
FIGHTERINFO_HEROS_FIELD.label = 3
FIGHTERINFO_HEROS_FIELD.has_default_value = false
FIGHTERINFO_HEROS_FIELD.default_value = {}
FIGHTERINFO_HEROS_FIELD.message_type = PVPHEROINFO
FIGHTERINFO_HEROS_FIELD.type = 11
FIGHTERINFO_HEROS_FIELD.cpp_type = 10

FIGHTERINFO.name = "FighterInfo"
FIGHTERINFO.full_name = ".Cmd.FighterInfo"
FIGHTERINFO.nested_types = {}
FIGHTERINFO.enum_types = {}
FIGHTERINFO.fields = {FIGHTERINFO_UID_FIELD, FIGHTERINFO_HEROS_FIELD}
FIGHTERINFO.is_extendable = false
FIGHTERINFO.extensions = {}

FighterInfo = protobuf.Message(FIGHTERINFO)
PvpHeroInfo = protobuf.Message(PVPHEROINFO)

