//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: activity.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: itemtype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityInfoReq")]
  public partial class ActivityInfoReq : global::ProtoBuf.IExtensible
  {
    public ActivityInfoReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ACTIVITY_INFO_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ACTIVITY_INFO_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityInfoRet")]
  public partial class ActivityInfoRet : global::ProtoBuf.IExtensible
  {
    public ActivityInfoRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ACTIVITY_INFO_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ACTIVITY_INFO_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _signDay;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint signDay
    {
      get { return _signDay; }
      set { _signDay = value; }
    }
    private uint _signFlag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"signFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint signFlag
    {
      get { return _signFlag; }
      set { _signFlag = value; }
    }
    private uint _spaTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"spaTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spaTime
    {
      get { return _spaTime; }
      set { _spaTime = value; }
    }
    private uint _mcardTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mcardTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mcardTime
    {
      get { return _mcardTime; }
      set { _mcardTime = value; }
    }
    private uint _mcardFlag;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"mcardFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mcardFlag
    {
      get { return _mcardFlag; }
      set { _mcardFlag = value; }
    }
    private uint _mcardCash;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mcardCash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mcardCash
    {
      get { return _mcardCash; }
      set { _mcardCash = value; }
    }
    private uint _fillCheck;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"fillCheck", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fillCheck
    {
      get { return _fillCheck; }
      set { _fillCheck = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpaReq")]
  public partial class SpaReq : global::ProtoBuf.IExtensible
  {
    public SpaReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SPA_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SPA_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpaRet")]
  public partial class SpaRet : global::ProtoBuf.IExtensible
  {
    public SpaRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SPA_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SPA_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _addEnergy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"addEnergy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint addEnergy
    {
      get { return _addEnergy; }
      set { _addEnergy = value; }
    }
    private uint _spaTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"spaTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spaTime
    {
      get { return _spaTime; }
      set { _spaTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailySignReq")]
  public partial class DailySignReq : global::ProtoBuf.IExtensible
  {
    public DailySignReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.DAILY_SIGN_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.DAILY_SIGN_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailySignRet")]
  public partial class DailySignRet : global::ProtoBuf.IExtensible
  {
    public DailySignRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.DAILY_SIGN_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.DAILY_SIGN_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _signDay;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint signDay
    {
      get { return _signDay; }
      set { _signDay = value; }
    }
    private uint _signFlag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"signFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint signFlag
    {
      get { return _signFlag; }
      set { _signFlag = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ItemNotiType> _item = new global::System.Collections.Generic.List<Cmd.ItemNotiType>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ItemNotiType> item
    {
      get { return _item; }
    }
  
    private uint _fillCheck;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fillCheck", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fillCheck
    {
      get { return _fillCheck; }
      set { _fillCheck = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonthCardBuyReq")]
  public partial class MonthCardBuyReq : global::ProtoBuf.IExtensible
  {
    public MonthCardBuyReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.MONTHCARD_BUY_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.MONTHCARD_BUY_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _transactionId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"transactionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string transactionId
    {
      get { return _transactionId; }
      set { _transactionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonthCardBuyRet")]
  public partial class MonthCardBuyRet : global::ProtoBuf.IExtensible
  {
    public MonthCardBuyRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.MONTHCARD_BUY_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.MONTHCARD_BUY_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _mcardTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mcardTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mcardTime
    {
      get { return _mcardTime; }
      set { _mcardTime = value; }
    }
    private uint _cash;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonthCardRewardReq")]
  public partial class MonthCardRewardReq : global::ProtoBuf.IExtensible
  {
    public MonthCardRewardReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.MONTHCARD_REWARD_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.MONTHCARD_REWARD_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonthCardRewardRet")]
  public partial class MonthCardRewardRet : global::ProtoBuf.IExtensible
  {
    public MonthCardRewardRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.MONTHCARD_REWARD_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.MONTHCARD_REWARD_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _mcardFlag;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mcardFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mcardFlag
    {
      get { return _mcardFlag; }
      set { _mcardFlag = value; }
    }
    private uint _cash;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private uint _mcardCash;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mcardCash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mcardCash
    {
      get { return _mcardCash; }
      set { _mcardCash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}