//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: rank.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: ranktype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRankInfoReq")]
  public partial class GetRankInfoReq : global::ProtoBuf.IExtensible
  {
    public GetRankInfoReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.RANK_INFO_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.RANK_INFO_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _rankType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType; }
      set { _rankType = value; }
    }
    private uint _start;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint start
    {
      get { return _start; }
      set { _start = value; }
    }
    private uint _end;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint end
    {
      get { return _end; }
      set { _end = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRankInfoRet")]
  public partial class GetRankInfoRet : global::ProtoBuf.IExtensible
  {
    public GetRankInfoRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.RANK_INFO_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.RANK_INFO_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _rank = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private uint _score = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.RankUnit> _player = new global::System.Collections.Generic.List<Cmd.RankUnit>();
    [global::ProtoBuf.ProtoMember(5, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.RankUnit> player
    {
      get { return _player; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}