//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: scene.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: scenetype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterCity")]
  public partial class MessageEnterCity : global::ProtoBuf.IExtensible
  {
    public MessageEnterCity() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ENTERCITY_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ENTERCITY_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _cityid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cityid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cityid
    {
      get { return _cityid; }
      set { _cityid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterCopy")]
  public partial class MessageEnterCopy : global::ProtoBuf.IExtensible
  {
    public MessageEnterCopy() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ENTERCOPY_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ENTERCOPY_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _copyid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterCopyNotify")]
  public partial class MessageEnterCopyNotify : global::ProtoBuf.IExtensible
  {
    public MessageEnterCopyNotify() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ENTERCOPY_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ENTERCOPY_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _copyid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private Cmd.FightMode _mode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.FightMode mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private int _buffseed = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buffseed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buffseed
    {
      get { return _buffseed; }
      set { _buffseed = value; }
    }
    private int _monsterseed = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"monsterseed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monsterseed
    {
      get { return _monsterseed; }
      set { _monsterseed = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.CopyUnitInfo> _unitlist = new global::System.Collections.Generic.List<Cmd.CopyUnitInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"unitlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.CopyUnitInfo> unitlist
    {
      get { return _unitlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterCopyPkNotify")]
  public partial class MessageEnterCopyPkNotify : global::ProtoBuf.IExtensible
  {
    public MessageEnterCopyPkNotify() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ENTERCOPYPK_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ENTERCOPYPK_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _copyid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.PkCopyUnitInfo> _unitlist = new global::System.Collections.Generic.List<Cmd.PkCopyUnitInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"unitlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.PkCopyUnitInfo> unitlist
    {
      get { return _unitlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageCopyReady")]
  public partial class MessageCopyReady : global::ProtoBuf.IExtensible
  {
    public MessageCopyReady() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_COPYREADY_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_COPYREADY_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageStartFight")]
  public partial class MessageStartFight : global::ProtoBuf.IExtensible
  {
    public MessageStartFight() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_STARTFIGHT_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_STARTFIGHT_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageExitCopy")]
  public partial class MessageExitCopy : global::ProtoBuf.IExtensible
  {
    public MessageExitCopy() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_EXITCOPY_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_EXITCOPY_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterScene")]
  public partial class MessageEnterScene : global::ProtoBuf.IExtensible
  {
    public MessageEnterScene() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ENTERSCENE_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ENTERSCENE_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _sceneid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sceneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sceneid
    {
      get { return _sceneid; }
      set { _sceneid = value; }
    }
    private int _pos_x = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageLeaveScene")]
  public partial class MessageLeaveScene : global::ProtoBuf.IExtensible
  {
    public MessageLeaveScene() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_LEAVESCENE_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_LEAVESCENE_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageTalkNpcRequest")]
  public partial class MessageTalkNpcRequest : global::ProtoBuf.IExtensible
  {
    public MessageTalkNpcRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_TALKNPC_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_TALKNPC_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _npcid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"npcid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npcid
    {
      get { return _npcid; }
      set { _npcid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageCopyListRequest")]
  public partial class MessageCopyListRequest : global::ProtoBuf.IExtensible
  {
    public MessageCopyListRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_COPYLIST_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_COPYLIST_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageCopyListResponse")]
  public partial class MessageCopyListResponse : global::ProtoBuf.IExtensible
  {
    public MessageCopyListResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_COPYLIST_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_COPYLIST_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.CopyStatusInfo> _list = new global::System.Collections.Generic.List<Cmd.CopyStatusInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.CopyStatusInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBuyItemRequest")]
  public partial class MessageBuyItemRequest : global::ProtoBuf.IExtensible
  {
    public MessageBuyItemRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BUYITME_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BUYITME_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _shopid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"shopid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint shopid
    {
      get { return _shopid; }
      set { _shopid = value; }
    }
    private uint _shoptype = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"shoptype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shoptype
    {
      get { return _shoptype; }
      set { _shoptype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBuyItemResponse")]
  public partial class MessageBuyItemResponse : global::ProtoBuf.IExtensible
  {
    public MessageBuyItemResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BUYITEM_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BUYITEM_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _shopid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"shopid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint shopid
    {
      get { return _shopid; }
      set { _shopid = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _creditcoin = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"creditcoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint creditcoin
    {
      get { return _creditcoin; }
      set { _creditcoin = value; }
    }
    private uint _shoptype = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"shoptype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shoptype
    {
      get { return _shoptype; }
      set { _shoptype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageRefreshShopRequest")]
  public partial class MessageRefreshShopRequest : global::ProtoBuf.IExtensible
  {
    public MessageRefreshShopRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_REFRESHSHOP_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_REFRESHSHOP_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _shoptype = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"shoptype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shoptype
    {
      get { return _shoptype; }
      set { _shoptype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageRefreshShopResponse")]
  public partial class MessageRefreshShopResponse : global::ProtoBuf.IExtensible
  {
    public MessageRefreshShopResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_REFRESHSHOP_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_REFRESHSHOP_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _timestamp = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private uint _shoptype = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"shoptype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shoptype
    {
      get { return _shoptype; }
      set { _shoptype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetShopRequest")]
  public partial class MessageGetShopRequest : global::ProtoBuf.IExtensible
  {
    public MessageGetShopRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_GETSHOPS_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_GETSHOPS_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageShopsNotice")]
  public partial class MessageShopsNotice : global::ProtoBuf.IExtensible
  {
    public MessageShopsNotice() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_SENDSHOPS_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_SENDSHOPS_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ShopUnitInfo> _list = new global::System.Collections.Generic.List<Cmd.ShopUnitInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ShopUnitInfo> list
    {
      get { return _list; }
    }
  
    private uint _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _creditcoin = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"creditcoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint creditcoin
    {
      get { return _creditcoin; }
      set { _creditcoin = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBattleReviveRequest")]
  public partial class MessageBattleReviveRequest : global::ProtoBuf.IExtensible
  {
    public MessageBattleReviveRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLEREVIVE_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLEREVIVE_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _isfree = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isfree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isfree
    {
      get { return _isfree; }
      set { _isfree = value; }
    }
    private uint _sequence = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageMonsterReviveRequest")]
  public partial class MessageMonsterReviveRequest : global::ProtoBuf.IExtensible
  {
    public MessageMonsterReviveRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_MONSTERREVIVE_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_MONSTERREVIVE_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _unitids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"unitids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> unitids
    {
      get { return _unitids; }
    }
  
    private uint _sequence = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageAgreePKRequest")]
  public partial class MessageAgreePKRequest : global::ProtoBuf.IExtensible
  {
    public MessageAgreePKRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_AGREEPK_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_AGREEPK_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _inviteid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"inviteid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong inviteid
    {
      get { return _inviteid; }
      set { _inviteid = value; }
    }
    private uint _serverid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"serverid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint serverid
    {
      get { return _serverid; }
      set { _serverid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageStartSweepRequest")]
  public partial class MessageStartSweepRequest : global::ProtoBuf.IExtensible
  {
    public MessageStartSweepRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_SWEEP_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_SWEEP_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _copyid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private uint _nums;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint nums
    {
      get { return _nums; }
      set { _nums = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEndSweepResponse")]
  public partial class MessageEndSweepResponse : global::ProtoBuf.IExtensible
  {
    public MessageEndSweepResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_SWEEP_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_SWEEP_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.SweepUnitInfo> _rewards = new global::System.Collections.Generic.List<Cmd.SweepUnitInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.SweepUnitInfo> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBuyCopyNumRequest")]
  public partial class MessageBuyCopyNumRequest : global::ProtoBuf.IExtensible
  {
    public MessageBuyCopyNumRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BUYCOPYNUM_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BUYCOPYNUM_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _copyid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBuyCopyNumResponse")]
  public partial class MessageBuyCopyNumResponse : global::ProtoBuf.IExtensible
  {
    public MessageBuyCopyNumResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BUYCOPYNUM_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BUYCOPYNUM_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _copyid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private uint _nums;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint nums
    {
      get { return _nums; }
      set { _nums = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetChapterRewardInfoRequest")]
  public partial class MessageGetChapterRewardInfoRequest : global::ProtoBuf.IExtensible
  {
    public MessageGetChapterRewardInfoRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_CHAPTERREWARDINFO_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_CHAPTERREWARDINFO_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teleid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teleid
    {
      get { return _teleid; }
      set { _teleid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetChapterRewardInfoResponse")]
  public partial class MessageGetChapterRewardInfoResponse : global::ProtoBuf.IExtensible
  {
    public MessageGetChapterRewardInfoResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_CHAPTERREWARDINFO_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_CHAPTERREWARDINFO_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teleid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teleid
    {
      get { return _teleid; }
      set { _teleid = value; }
    }
    private uint _value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetChapterRewardRequest")]
  public partial class MessageGetChapterRewardRequest : global::ProtoBuf.IExtensible
  {
    public MessageGetChapterRewardRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_CHAPTERREWARD_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_CHAPTERREWARD_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teleid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teleid
    {
      get { return _teleid; }
      set { _teleid = value; }
    }
    private uint _rwdtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rwdtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rwdtype
    {
      get { return _rwdtype; }
      set { _rwdtype = value; }
    }
    private uint _teltype;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"teltype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teltype
    {
      get { return _teltype; }
      set { _teltype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetChapterRewardResponse")]
  public partial class MessageGetChapterRewardResponse : global::ProtoBuf.IExtensible
  {
    public MessageGetChapterRewardResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_CHAPTERREWARD_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_CHAPTERREWARD_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.CopyRewards> _rewards = new global::System.Collections.Generic.List<Cmd.CopyRewards>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.CopyRewards> rewards
    {
      get { return _rewards; }
    }
  
    private uint _rwdtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rwdtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rwdtype
    {
      get { return _rwdtype; }
      set { _rwdtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetGiftRequest")]
  public partial class MessageGetGiftRequest : global::ProtoBuf.IExtensible
  {
    public MessageGetGiftRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_GETGIFT_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_GETGIFT_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _gift;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gift", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gift
    {
      get { return _gift; }
      set { _gift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetGiftResponse")]
  public partial class MessageGetGiftResponse : global::ProtoBuf.IExtensible
  {
    public MessageGetGiftResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_GETGIFT_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_GETGIFT_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.CopyRewards> _rewards = new global::System.Collections.Generic.List<Cmd.CopyRewards>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.CopyRewards> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageRobotsRequest")]
  public partial class MessageRobotsRequest : global::ProtoBuf.IExtensible
  {
    public MessageRobotsRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ROBOTS_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ROBOTS_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageRobotsResponse")]
  public partial class MessageRobotsResponse : global::ProtoBuf.IExtensible
  {
    public MessageRobotsResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ROBOTS_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ROBOTS_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.RobotUnit> _robots = new global::System.Collections.Generic.List<Cmd.RobotUnit>();
    [global::ProtoBuf.ProtoMember(2, Name=@"robots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.RobotUnit> robots
    {
      get { return _robots; }
    }
  
    private bool _isover = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isover
    {
      get { return _isover; }
      set { _isover = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterSoulFightNotify")]
  public partial class MessageEnterSoulFightNotify : global::ProtoBuf.IExtensible
  {
    public MessageEnterSoulFightNotify() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_SOULFIGHT_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_SOULFIGHT_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _perfectID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"perfectID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint perfectID
    {
      get { return _perfectID; }
      set { _perfectID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageOpenCityNotify")]
  public partial class MessageOpenCityNotify : global::ProtoBuf.IExtensible
  {
    public MessageOpenCityNotify() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_OPENCITY_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_OPENCITY_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _citys = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"citys", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> citys
    {
      get { return _citys; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterClimbTowerCopyReq")]
  public partial class MessageEnterClimbTowerCopyReq : global::ProtoBuf.IExtensible
  {
    public MessageEnterClimbTowerCopyReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ENTER_CLIMBTOWERCOPY_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ENTER_CLIMBTOWERCOPY_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterWorldCopyRet")]
  public partial class MessageEnterWorldCopyRet : global::ProtoBuf.IExtensible
  {
    public MessageEnterWorldCopyRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_ENTER_WORLDCOPY_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_ENTER_WORLDCOPY_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _bossid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bossid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong bossid
    {
      get { return _bossid; }
      set { _bossid = value; }
    }
    private uint _bosshp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bosshp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bosshp
    {
      get { return _bosshp; }
      set { _bosshp = value; }
    }
    private uint _hitdown = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hitdown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hitdown
    {
      get { return _hitdown; }
      set { _hitdown = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _unitids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(5, Name=@"unitids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> unitids
    {
      get { return _unitids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageWait4StartReq")]
  public partial class MessageWait4StartReq : global::ProtoBuf.IExtensible
  {
    public MessageWait4StartReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_WAIT4START_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_WAIT4START_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetBattleSquareReq")]
  public partial class MessageGetBattleSquareReq : global::ProtoBuf.IExtensible
  {
    public MessageGetBattleSquareReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetBattleSquareRet")]
  public partial class MessageGetBattleSquareRet : global::ProtoBuf.IExtensible
  {
    public MessageGetBattleSquareRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _starttime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"starttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint starttime
    {
      get { return _starttime; }
      set { _starttime = value; }
    }
    private uint _wintimes = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wintimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wintimes
    {
      get { return _wintimes; }
      set { _wintimes = value; }
    }
    private uint _rank = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private uint _score = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _rewardflag = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rewardflag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rewardflag
    {
      get { return _rewardflag; }
      set { _rewardflag = value; }
    }
    private uint _isopen = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isopen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isopen
    {
      get { return _isopen; }
      set { _isopen = value; }
    }
    private uint _isbet = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"isbet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isbet
    {
      get { return _isbet; }
      set { _isbet = value; }
    }
    private uint _seasons = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"seasons", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seasons
    {
      get { return _seasons; }
      set { _seasons = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBattleSquareBetReq")]
  public partial class MessageBattleSquareBetReq : global::ProtoBuf.IExtensible
  {
    public MessageBattleSquareBetReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUAREBAT_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUAREBAT_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _index = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBattleSquareBetRet")]
  public partial class MessageBattleSquareBetRet : global::ProtoBuf.IExtensible
  {
    public MessageBattleSquareBetRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUAREBAT_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUAREBAT_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBattleSquareMatchReq")]
  public partial class MessageBattleSquareMatchReq : global::ProtoBuf.IExtensible
  {
    public MessageBattleSquareMatchReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_MATCH_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_MATCH_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBattleSquareMatchRet")]
  public partial class MessageBattleSquareMatchRet : global::ProtoBuf.IExtensible
  {
    public MessageBattleSquareMatchRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_MATCH_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_MATCH_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _defid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"defid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong defid
    {
      get { return _defid; }
      set { _defid = value; }
    }
    private string _defname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"defname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string defname
    {
      get { return _defname; }
      set { _defname = value; }
    }
    private uint _score = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _rank = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageBattleSquareFight")]
  public partial class MessageBattleSquareFight : global::ProtoBuf.IExtensible
  {
    public MessageBattleSquareFight() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_FIGHT_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_FIGHT_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetBattleSquareRewdReq")]
  public partial class MessageGetBattleSquareRewdReq : global::ProtoBuf.IExtensible
  {
    public MessageGetBattleSquareRewdReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_REWARD_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_REWARD_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetBattleSquareRewdRet")]
  public partial class MessageGetBattleSquareRewdRet : global::ProtoBuf.IExtensible
  {
    public MessageGetBattleSquareRewdRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_REWARD_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_REWARD_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetBattleSquareRecordReq")]
  public partial class MessageGetBattleSquareRecordReq : global::ProtoBuf.IExtensible
  {
    public MessageGetBattleSquareRecordReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_RECORD_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_RECORD_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetBattleSquareRecordRet")]
  public partial class MessageGetBattleSquareRecordRet : global::ProtoBuf.IExtensible
  {
    public MessageGetBattleSquareRecordRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SCENE_BATTLESQUARE_RECORD_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SCENE_BATTLESQUARE_RECORD_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.BattleSquareInfo> _list = new global::System.Collections.Generic.List<Cmd.BattleSquareInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.BattleSquareInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}