//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: soultype.proto
// Note: requires additional types generated from: roletype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulInfo")]
  public partial class SoulInfo : global::ProtoBuf.IExtensible
  {
    public SoulInfo() {}
    
    private ulong _thisid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _soulid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"soulid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint soulid
    {
      get { return _soulid; }
      set { _soulid = value; }
    }
    private ulong _exp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _equipindex;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint equipindex
    {
      get { return _equipindex; }
      set { _equipindex = value; }
    }
    private uint _grade = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulFightBlade")]
  public partial class SoulFightBlade : global::ProtoBuf.IExtensible
  {
    public SoulFightBlade() {}
    
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _sp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sp
    {
      get { return _sp; }
      set { _sp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulFightPlayer")]
  public partial class SoulFightPlayer : global::ProtoBuf.IExtensible
  {
    public SoulFightPlayer() {}
    
    private ulong _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private uint _winFlag;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"winFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint winFlag
    {
      get { return _winFlag; }
      set { _winFlag = value; }
    }
    private uint _winCond = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"winCond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint winCond
    {
      get { return _winCond; }
      set { _winCond = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.SoulFightBlade> _blade = new global::System.Collections.Generic.List<Cmd.SoulFightBlade>();
    [global::ProtoBuf.ProtoMember(10, Name=@"blade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.SoulFightBlade> blade
    {
      get { return _blade; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}