//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: training.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: scenetype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageCommandPhoneInfoRequest")]
  public partial class MessageCommandPhoneInfoRequest : global::ProtoBuf.IExtensible
  {
    public MessageCommandPhoneInfoRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.COMMANDPHONE_INFO_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.COMMANDPHONE_INFO_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageCommandPhoneInfoNotice")]
  public partial class MessageCommandPhoneInfoNotice : global::ProtoBuf.IExtensible
  {
    public MessageCommandPhoneInfoNotice() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.COMMANDPHONE_INFO_RSP;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.COMMANDPHONE_INFO_RSP)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private uint _cdtime = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cdtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cdtime
    {
      get { return _cdtime; }
      set { _cdtime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterCommandPhoneReq")]
  public partial class MessageEnterCommandPhoneReq : global::ProtoBuf.IExtensible
  {
    public MessageEnterCommandPhoneReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ENTER_COMMANDPHONE_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ENTER_COMMANDPHONE_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _copyid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageSoulRoomInfoRequest")]
  public partial class MessageSoulRoomInfoRequest : global::ProtoBuf.IExtensible
  {
    public MessageSoulRoomInfoRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SOULROOM_INFO_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SOULROOM_INFO_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageSoulRoomInfoNotice")]
  public partial class MessageSoulRoomInfoNotice : global::ProtoBuf.IExtensible
  {
    public MessageSoulRoomInfoNotice() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SOULROOM_INFO_RSP;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SOULROOM_INFO_RSP)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private uint _cdtime = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cdtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cdtime
    {
      get { return _cdtime; }
      set { _cdtime = value; }
    }
    private uint _emergencyTimes = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"emergencyTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint emergencyTimes
    {
      get { return _emergencyTimes; }
      set { _emergencyTimes = value; }
    }
    private uint _buytimes = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buytimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint buytimes
    {
      get { return _buytimes; }
      set { _buytimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnterSoulRoomReq")]
  public partial class MessageEnterSoulRoomReq : global::ProtoBuf.IExtensible
  {
    public MessageEnterSoulRoomReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ENTER_SOULROOM_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ENTER_SOULROOM_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _copyid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulRoomBuyTimesReq")]
  public partial class SoulRoomBuyTimesReq : global::ProtoBuf.IExtensible
  {
    public SoulRoomBuyTimesReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SOULROOM_BUYTIMES_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SOULROOM_BUYTIMES_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulRoomBuyTimesRet")]
  public partial class SoulRoomBuyTimesRet : global::ProtoBuf.IExtensible
  {
    public SoulRoomBuyTimesRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SOULROOM_BUYTIMES_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SOULROOM_BUYTIMES_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _buytimes = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buytimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint buytimes
    {
      get { return _buytimes; }
      set { _buytimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}