//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: basetype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleAvatar")]
  public partial class RoleAvatar : global::ProtoBuf.IExtensible
  {
    public RoleAvatar() {}
    
    private ulong _roleid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private int _dress;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dress
    {
      get { return _dress; }
      set { _dress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulIndex")]
  public partial class SoulIndex : global::ProtoBuf.IExtensible
  {
    public SoulIndex() {}
    
    private ulong _thisid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _equipindex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint equipindex
    {
      get { return _equipindex; }
      set { _equipindex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EProtoId")]
    public enum EProtoId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TICK_CMD", Value=0)]
      TICK_CMD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CMD", Value=65280)]
      ERROR_CMD = 65280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CODE_S", Value=65281)]
      ERROR_CODE_S = 65281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CMD", Value=256)]
      LOGIN_CMD = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VERIFY_VERSION", Value=257)]
      VERIFY_VERSION = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOGIN_REQ", Value=258)]
      LOGIN_LOGIN_REQ = 258,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOGIN_RET", Value=259)]
      LOGIN_LOGIN_RET = 259,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_GATEW_REQ", Value=260)]
      LOGIN_GATEW_REQ = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_GATEW_RET", Value=261)]
      LOGIN_GATEW_RET = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_OFFLINE", Value=262)]
      FORCE_OFFLINE = 262,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEMP_CREDENTIAL_REQ", Value=263)]
      TEMP_CREDENTIAL_REQ = 263,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEMP_CREDENTIAL_RET", Value=264)]
      TEMP_CREDENTIAL_RET = 264,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_TRANSIT_REQ", Value=265)]
      LOGIN_TRANSIT_REQ = 265,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_TRANSIT_RET", Value=266)]
      LOGIN_TRANSIT_RET = 266,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_CMD", Value=512)]
      ROLE_CMD = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_ROLE_LIST", Value=513)]
      SEND_ROLE_LIST = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELECT_ROLE_ONLINE", Value=514)]
      SELECT_ROLE_ONLINE = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_ROLE_REQ", Value=515)]
      CREATE_ROLE_REQ = 515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_ROLE_RET", Value=516)]
      CREATE_ROLE_RET = 516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_ROLE_DATA", Value=517)]
      SEND_ROLE_DATA = 517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_ATTRCHANGES_S", Value=518)]
      ROLE_ATTRCHANGES_S = 518,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_GETBUFF_C", Value=519)]
      ROLE_GETBUFF_C = 519,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_GETBUFF_S", Value=520)]
      ROLE_GETBUFF_S = 520,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_MACHINE_C", Value=521)]
      GOLD_MACHINE_C = 521,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_MACHINE_S", Value=528)]
      GOLD_MACHINE_S = 528,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_ENERGY_C", Value=529)]
      BUY_ENERGY_C = 529,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_ENERGY_S", Value=530)]
      BUY_ENERGY_S = 530,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_CHANGE_NICK_C", Value=531)]
      ROLE_CHANGE_NICK_C = 531,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_USE_MB_C", Value=532)]
      BUY_USE_MB_C = 532,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_USE_MB_S", Value=533)]
      BUY_USE_MB_S = 533,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENT_ROLE_OFFLINE", Value=534)]
      CURRENT_ROLE_OFFLINE = 534,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_GUIDE_STEP", Value=535)]
      UPDATE_GUIDE_STEP = 535,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VIP_CHANGE_NOTI_S", Value=537)]
      VIP_CHANGE_NOTI_S = 537,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_DRESS_C", Value=538)]
      GET_DRESS_C = 538,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_DRESS_S", Value=539)]
      GET_DRESS_S = 539,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_DRESS_C", Value=540)]
      EQUIP_DRESS_C = 540,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_DRESS_S", Value=541)]
      EQUIP_DRESS_S = 541,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE_DRESS_C", Value=542)]
      UPGRADE_DRESS_C = 542,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE_DRESS_S", Value=543)]
      UPGRADE_DRESS_S = 543,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYNC_EQUIPDRESS_S", Value=544)]
      SYNC_EQUIPDRESS_S = 544,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCKKONT_OPEN_C", Value=545)]
      LOCKKONT_OPEN_C = 545,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCKKONT_OPEN_S", Value=546)]
      LOCKKONT_OPEN_S = 546,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_CHANGE_NICK_S", Value=547)]
      ROLE_CHANGE_NICK_S = 547,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MARQUEE_NOTI_S", Value=548)]
      MARQUEE_NOTI_S = 548,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_CLIMBTOWER_C", Value=549)]
      GET_CLIMBTOWER_C = 549,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_CLIMBTOWER_S", Value=550)]
      GET_CLIMBTOWER_S = 550,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_CLIMBTOWERTIMES_C", Value=551)]
      BUY_CLIMBTOWERTIMES_C = 551,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_CLIMBTOWERTIMES_S", Value=552)]
      BUY_CLIMBTOWERTIMES_S = 552,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBTAIN_CLIMBTOWERREWARD_C", Value=553)]
      OBTAIN_CLIMBTOWERREWARD_C = 553,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBTAIN_CLIMBTOWERREWARD_S", Value=554)]
      OBTAIN_CLIMBTOWERREWARD_S = 554,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROLEINFO_C", Value=556)]
      GET_ROLEINFO_C = 556,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROLEiNFO_S", Value=557)]
      GET_ROLEiNFO_S = 557,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELECT_CLIMBTOWER_TYPE_C", Value=558)]
      SELECT_CLIMBTOWER_TYPE_C = 558,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELECT_CLIMBTOWER_TYPE_S", Value=560)]
      SELECT_CLIMBTOWER_TYPE_S = 560,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESET_CLIMBTOWER_COPY_C", Value=561)]
      RESET_CLIMBTOWER_COPY_C = 561,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESET_CLIMBTOWER_COPY_S", Value=562)]
      RESET_CLIMBTOWER_COPY_S = 562,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ACTION_C", Value=563)]
      GET_ACTION_C = 563,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ACTIONREWARD_C", Value=565)]
      GET_ACTIONREWARD_C = 565,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ACTIONREWARD_S", Value=566)]
      GET_ACTIONREWARD_S = 566,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_ACTION_S", Value=567)]
      SEND_ACTION_S = 567,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_DATA_LOAD_OK", Value=568)]
      ROLE_DATA_LOAD_OK = 568,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_RED_POINT_S", Value=569)]
      SEND_RED_POINT_S = 569,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_BP_C", Value=576)]
      UPDATE_BP_C = 576,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_RECHARGE_INFO_C", Value=577)]
      GET_RECHARGE_INFO_C = 577,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_RECHARGE_INFO_S", Value=578)]
      GET_RECHARGE_INFO_S = 578,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ACTIONRANK_C", Value=579)]
      GET_ACTIONRANK_C = 579,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_ACTIONRANK_S", Value=580)]
      SEND_ACTIONRANK_S = 580,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROLELIST_C", Value=581)]
      GET_ROLELIST_C = 581,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROLELIST_S", Value=582)]
      GET_ROLELIST_S = 582,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_BAN_S", Value=583)]
      CHAT_BAN_S = 583,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_FIRST_CHARGE_REWARD_C", Value=584)]
      GET_FIRST_CHARGE_REWARD_C = 584,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_FIRST_CHARGE_REWARD_S", Value=585)]
      GET_FIRST_CHARGE_REWARD_S = 585,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_TEST_FEEDBACK_INFO_S", Value=592)]
      GET_TEST_FEEDBACK_INFO_S = 592,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_TEST_FEEDBACK_GIFT_C", Value=593)]
      GET_TEST_FEEDBACK_GIFT_C = 593,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_TEST_FEEDBACK_GIFT_S", Value=594)]
      GET_TEST_FEEDBACK_GIFT_S = 594,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_CHARGE_FEEDBACK_INFO_S", Value=595)]
      GET_CHARGE_FEEDBACK_INFO_S = 595,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_CHARGE_FEEDBACK_GIFT_C", Value=596)]
      GET_CHARGE_FEEDBACK_GIFT_C = 596,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_CHARGE_FEEDBACK_GIFT_S", Value=597)]
      GET_CHARGE_FEEDBACK_GIFT_S = 597,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_VIP_REWARD_C", Value=598)]
      GET_VIP_REWARD_C = 598,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_VIP_REWARD_S", Value=599)]
      GET_VIP_REWARD_S = 599,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULCORE_GET_INFO_C", Value=600)]
      SOULCORE_GET_INFO_C = 600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULCORE_GET_INFO_S", Value=601)]
      SOULCORE_GET_INFO_S = 601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULCORE_PRACTICE_C", Value=608)]
      SOULCORE_PRACTICE_C = 608,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULCORE_PRACTICE_S", Value=609)]
      SOULCORE_PRACTICE_S = 609,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULCORE_SAVE_C", Value=610)]
      SOULCORE_SAVE_C = 610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULCORE_SAVE_S", Value=611)]
      SOULCORE_SAVE_S = 611,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_FREE_REWARD_C", Value=612)]
      GET_FREE_REWARD_C = 612,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_FREE_REWARD_S", Value=613)]
      GET_FREE_REWARD_S = 613,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_STRONG_C", Value=614)]
      GET_STRONG_C = 614,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_STRONG_S", Value=615)]
      GET_STRONG_S = 615,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_TEST_FEEDBACK2_INFO_S", Value=616)]
      GET_TEST_FEEDBACK2_INFO_S = 616,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_TEST_FEEDBACK2_GIFT_C", Value=617)]
      GET_TEST_FEEDBACK2_GIFT_C = 617,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_TEST_FEEDBACK2_GIFT_S", Value=618)]
      GET_TEST_FEEDBACK2_GIFT_S = 618,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_CMD", Value=768)]
      SCENE_CMD = 768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ENTERCOPY_C", Value=769)]
      SCENE_ENTERCOPY_C = 769,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ENTERCOPY_S", Value=770)]
      SCENE_ENTERCOPY_S = 770,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_COPYREADY_C", Value=771)]
      SCENE_COPYREADY_C = 771,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_STARTFIGHT_S", Value=772)]
      SCENE_STARTFIGHT_S = 772,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_EXITCOPY_C", Value=773)]
      SCENE_EXITCOPY_C = 773,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ENTERCITY_C", Value=774)]
      SCENE_ENTERCITY_C = 774,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ENTERSCENE_S", Value=775)]
      SCENE_ENTERSCENE_S = 775,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_LEAVESCENE_S", Value=776)]
      SCENE_LEAVESCENE_S = 776,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_TALKNPC_C", Value=777)]
      SCENE_TALKNPC_C = 777,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_COPYLIST_C", Value=778)]
      SCENE_COPYLIST_C = 778,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_COPYLIST_S", Value=779)]
      SCENE_COPYLIST_S = 779,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BUYITME_C", Value=780)]
      SCENE_BUYITME_C = 780,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BUYITEM_S", Value=781)]
      SCENE_BUYITEM_S = 781,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_REFRESHSHOP_C", Value=782)]
      SCENE_REFRESHSHOP_C = 782,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_REFRESHSHOP_S", Value=783)]
      SCENE_REFRESHSHOP_S = 783,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_GETSHOPS_C", Value=784)]
      SCENE_GETSHOPS_C = 784,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_SENDSHOPS_S", Value=785)]
      SCENE_SENDSHOPS_S = 785,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLEREVIVE_C", Value=786)]
      SCENE_BATTLEREVIVE_C = 786,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ENTERCOPYPK_S", Value=787)]
      SCENE_ENTERCOPYPK_S = 787,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_AGREEPK_C", Value=788)]
      SCENE_AGREEPK_C = 788,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_SWEEP_C", Value=789)]
      SCENE_SWEEP_C = 789,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_SWEEP_S", Value=790)]
      SCENE_SWEEP_S = 790,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BUYCOPYNUM_C", Value=791)]
      SCENE_BUYCOPYNUM_C = 791,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BUYCOPYNUM_S", Value=792)]
      SCENE_BUYCOPYNUM_S = 792,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_CHAPTERREWARD_C", Value=793)]
      SCENE_CHAPTERREWARD_C = 793,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_CHAPTERREWARD_S", Value=794)]
      SCENE_CHAPTERREWARD_S = 794,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_CHAPTERREWARDINFO_C", Value=795)]
      SCENE_CHAPTERREWARDINFO_C = 795,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_CHAPTERREWARDINFO_S", Value=796)]
      SCENE_CHAPTERREWARDINFO_S = 796,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_GETGIFT_C", Value=797)]
      SCENE_GETGIFT_C = 797,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_GETGIFT_S", Value=798)]
      SCENE_GETGIFT_S = 798,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_MONSTERREVIVE_C", Value=799)]
      SCENE_MONSTERREVIVE_C = 799,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ROBOTS_C", Value=800)]
      SCENE_ROBOTS_C = 800,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ROBOTS_S", Value=801)]
      SCENE_ROBOTS_S = 801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_SOULFIGHT_S", Value=802)]
      SCENE_SOULFIGHT_S = 802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_OPENCITY_S", Value=803)]
      SCENE_OPENCITY_S = 803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ENTER_CLIMBTOWERCOPY_C", Value=804)]
      SCENE_ENTER_CLIMBTOWERCOPY_C = 804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_ENTER_WORLDCOPY_S", Value=805)]
      SCENE_ENTER_WORLDCOPY_S = 805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_WAIT4START_C", Value=806)]
      SCENE_WAIT4START_C = 806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_C", Value=807)]
      SCENE_BATTLESQUARE_C = 807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_S", Value=808)]
      SCENE_BATTLESQUARE_S = 808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUAREBAT_C", Value=809)]
      SCENE_BATTLESQUAREBAT_C = 809,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUAREBAT_S", Value=810)]
      SCENE_BATTLESQUAREBAT_S = 810,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_MATCH_C", Value=811)]
      SCENE_BATTLESQUARE_MATCH_C = 811,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_MATCH_S", Value=812)]
      SCENE_BATTLESQUARE_MATCH_S = 812,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_FIGHT_C", Value=813)]
      SCENE_BATTLESQUARE_FIGHT_C = 813,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_REWARD_C", Value=814)]
      SCENE_BATTLESQUARE_REWARD_C = 814,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_REWARD_S", Value=815)]
      SCENE_BATTLESQUARE_REWARD_S = 815,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_RECORD_C", Value=816)]
      SCENE_BATTLESQUARE_RECORD_C = 816,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_BATTLESQUARE_RECORD_S", Value=817)]
      SCENE_BATTLESQUARE_RECORD_S = 817,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_CMD", Value=1024)]
      BLADE_CMD = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_BLADE_LIST", Value=1025)]
      SEND_BLADE_LIST = 1025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_STRENGTH_REQ", Value=1026)]
      BLADE_STRENGTH_REQ = 1026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_STRENGTH_RET", Value=1027)]
      BLADE_STRENGTH_RET = 1027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_BREAK_REQ", Value=1028)]
      BLADE_BREAK_REQ = 1028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_BREAK_RET", Value=1029)]
      BLADE_BREAK_RET = 1029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_EXCHANGE_REQ", Value=1030)]
      BLADE_EXCHANGE_REQ = 1030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_EXCHANGE_RET", Value=1031)]
      BLADE_EXCHANGE_RET = 1031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_LOTTERY_REQ", Value=1032)]
      BLADE_LOTTERY_REQ = 1032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_LOTTERY_RET", Value=1033)]
      BLADE_LOTTERY_RET = 1033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_UPGRADE_REQ", Value=1034)]
      SKILL_UPGRADE_REQ = 1034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_UPGRADE_RET", Value=1035)]
      SKILL_UPGRADE_RET = 1035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW_BLADE_LIST", Value=1036)]
      NEW_BLADE_LIST = 1036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_LIBERATION_REQ", Value=1037)]
      BLADE_LIBERATION_REQ = 1037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_LIBERATION_RET", Value=1038)]
      BLADE_LIBERATION_RET = 1038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_CMD", Value=1280)]
      ITEM_CMD = 1280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_ITEM_LIST", Value=1281)]
      SEND_ITEM_LIST = 1281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PIECE_TO_BLADE_REQ", Value=1282)]
      PIECE_TO_BLADE_REQ = 1282,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PIECE_TO_BLADE_RET", Value=1283)]
      PIECE_TO_BLADE_RET = 1283,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELL_ITEM_REQ", Value=1284)]
      SELL_ITEM_REQ = 1284,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELL_ITEM_RET", Value=1285)]
      SELL_ITEM_RET = 1285,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW_ITEM_LIST", Value=1288)]
      NEW_ITEM_LIST = 1288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_ITEM_LIST", Value=1289)]
      UPDATE_ITEM_LIST = 1289,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMOVE_ITEM_LIST", Value=1290)]
      REMOVE_ITEM_LIST = 1290,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PIECE_TO_SOUL_REQ", Value=1291)]
      PIECE_TO_SOUL_REQ = 1291,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PIECE_TO_SOUL_RET", Value=1292)]
      PIECE_TO_SOUL_RET = 1292,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPEN_ITEM_REQ", Value=1293)]
      OPEN_ITEM_REQ = 1293,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPEN_ITEM_RET", Value=1294)]
      OPEN_ITEM_RET = 1294,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PIECE_TO_REFINED_REQ", Value=1295)]
      PIECE_TO_REFINED_REQ = 1295,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PIECE_TO_REFINED_RET", Value=1296)]
      PIECE_TO_REFINED_RET = 1296,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_CMD", Value=1536)]
      TEAM_CMD = 1536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_TEAM_REQ", Value=1537)]
      CREATE_TEAM_REQ = 1537,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_TEAM_RET", Value=1538)]
      CREATE_TEAM_RET = 1538,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_JOIN_TEAM_REQ", Value=1539)]
      INVITE_JOIN_TEAM_REQ = 1539,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_JOIN_TEAM_RET", Value=1540)]
      INVITE_JOIN_TEAM_RET = 1540,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN_TEAM_REQ", Value=1541)]
      JOIN_TEAM_REQ = 1541,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN_TEAM_RET", Value=1542)]
      JOIN_TEAM_RET = 1542,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCH_TEAM_REQ", Value=1543)]
      MATCH_TEAM_REQ = 1543,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCH_TEAM_RET", Value=1544)]
      MATCH_TEAM_RET = 1544,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUIT_TEAM_REQ", Value=1545)]
      QUIT_TEAM_REQ = 1545,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUIT_TEAM_RET", Value=1546)]
      QUIT_TEAM_RET = 1546,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KICK_OUT_TEAM_REQ", Value=1547)]
      KICK_OUT_TEAM_REQ = 1547,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KICK_OUT_TEAM_RET", Value=1548)]
      KICK_OUT_TEAM_RET = 1548,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_TEAM_FIGHT_REQ", Value=1549)]
      START_TEAM_FIGHT_REQ = 1549,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_TEAM_FIGHT_RET", Value=1550)]
      START_TEAM_FIGHT_RET = 1550,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_LIST_REQ", Value=1551)]
      TEAM_LIST_REQ = 1551,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_LIST_RET", Value=1552)]
      TEAM_LIST_RET = 1552,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_CMD", Value=1792)]
      QUEST_CMD = 1792,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_QUESTLIST_C", Value=1793)]
      GET_QUESTLIST_C = 1793,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_QUESTLIST_S", Value=1794)]
      GET_QUESTLIST_S = 1794,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCEPT_QUEST_C", Value=1795)]
      ACCEPT_QUEST_C = 1795,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCEPT_QUEST_S", Value=1796)]
      ACCEPT_QUEST_S = 1796,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUBMIT_QUEST_C", Value=1797)]
      SUBMIT_QUEST_C = 1797,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUBMIT_QUEST_S", Value=1798)]
      SUBMIT_QUEST_S = 1798,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_PROGRESS_S", Value=1799)]
      QUEST_PROGRESS_S = 1799,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_DAILYQUEST_C", Value=1800)]
      GET_DAILYQUEST_C = 1800,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_DAILYQUEST_S", Value=1801)]
      GET_DAILYQUEST_S = 1801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_CMD", Value=2048)]
      MAIL_CMD = 2048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_MAIL_LIST", Value=2049)]
      SEND_MAIL_LIST = 2049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_NEW_MAIL", Value=2050)]
      SEND_NEW_MAIL = 2050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCEPT_MAIL_REQ", Value=2051)]
      ACCEPT_MAIL_REQ = 2051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCEPT_MAIL_RET", Value=2052)]
      ACCEPT_MAIL_RET = 2052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_LIST_REQ", Value=2053)]
      MAIL_LIST_REQ = 2053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_LIST_RET", Value=2054)]
      MAIL_LIST_RET = 2054,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_DEL_REQ", Value=2055)]
      MAIL_DEL_REQ = 2055,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_DEL_RET", Value=2056)]
      MAIL_DEL_RET = 2056,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UTILS_CMD", Value=2304)]
      UTILS_CMD = 2304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_TIME_REQ", Value=2305)]
      SERVER_TIME_REQ = 2305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_TIME_RET", Value=2306)]
      SERVER_TIME_RET = 2306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UTILS_ECHO", Value=2307)]
      UTILS_ECHO = 2307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CMD", Value=4096)]
      FIGHT_CMD = 4096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_WALK_CS", Value=4097)]
      FIGHT_WALK_CS = 4097,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_RUN_CS", Value=4098)]
      FIGHT_RUN_CS = 4098,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_JUMP_CS", Value=4099)]
      FIGHT_JUMP_CS = 4099,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_DIRECT_CS", Value=4100)]
      FIGHT_DIRECT_CS = 4100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_ATTACK_CS", Value=4101)]
      FIGHT_ATTACK_CS = 4101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_READY_CS", Value=4102)]
      FIGHT_READY_CS = 4102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_BLOOD_S", Value=4103)]
      FIGHT_BLOOD_S = 4103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_DIE_S", Value=4104)]
      FIGHT_DIE_S = 4104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_WAITRESULT_C", Value=4105)]
      FIGHT_WAITRESULT_C = 4105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_HIT_C", Value=4106)]
      FIGHT_HIT_C = 4106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_RESULT_S", Value=4107)]
      FIGHT_RESULT_S = 4107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CALCULATE_S", Value=4108)]
      FIGHT_CALCULATE_S = 4108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_LEAVE_S", Value=4109)]
      FIGHT_LEAVE_S = 4109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_SUSPEND_S", Value=4110)]
      FIGHT_SUSPEND_S = 4110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_SKILL_CS", Value=4111)]
      FIGHT_SKILL_CS = 4111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_WAIT4REVIVE_S", Value=4112)]
      FIGHT_WAIT4REVIVE_S = 4112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_DESTROY_S", Value=4113)]
      FIGHT_DESTROY_S = 4113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CROSS_C", Value=4114)]
      FIGHT_CROSS_C = 4114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CROSS_S", Value=4115)]
      FIGHT_CROSS_S = 4115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CHANGESWORD_C", Value=4116)]
      FIGHT_CHANGESWORD_C = 4116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CHANGESWORD_S", Value=4117)]
      FIGHT_CHANGESWORD_S = 4117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_REVIVE_S", Value=4118)]
      FIGHT_REVIVE_S = 4118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_BUFF_C", Value=4119)]
      FIGHT_BUFF_C = 4119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_ENDBUFF_C", Value=4120)]
      FIGHT_ENDBUFF_C = 4120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_DYING_C", Value=4121)]
      FIGHT_DYING_C = 4121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_RELEASESKILL_C", Value=4122)]
      FIGHT_RELEASESKILL_C = 4122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_RELEASEBULLET_C", Value=4123)]
      FIGHT_RELEASEBULLET_C = 4123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_ENDBULLET_C", Value=4124)]
      FIGHT_ENDBULLET_C = 4124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_SYNCREWARD_C", Value=4125)]
      FIGHT_SYNCREWARD_C = 4125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_SYNC_CS", Value=4126)]
      FIGHT_SYNC_CS = 4126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_SOULFIGHT_S", Value=4127)]
      FIGHT_SOULFIGHT_S = 4127,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_FIGHTAGAIN_C", Value=4128)]
      FIGHT_FIGHTAGAIN_C = 4128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_FIGHTAGAIN_S", Value=4129)]
      FIGHT_FIGHTAGAIN_S = 4129,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CALLSUMMON_C", Value=4130)]
      FIGHT_CALLSUMMON_C = 4130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CALLSUMMON_S", Value=4131)]
      FIGHT_CALLSUMMON_S = 4131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_ADD_CALCULATE_S", Value=4132)]
      FIGHT_ADD_CALCULATE_S = 4132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_TRIGGER_BUFF_C", Value=4133)]
      FIGHT_TRIGGER_BUFF_C = 4133,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_MONSTER_S", Value=4134)]
      FIGHT_MONSTER_S = 4134,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_CLIMBTOWERFIGHT_S", Value=4135)]
      FIGHT_CLIMBTOWERFIGHT_S = 4135,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_WORDZHUNAN_S", Value=4136)]
      FIGHT_WORDZHUNAN_S = 4136,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_GETHITSEQ_C", Value=4137)]
      FIGHT_GETHITSEQ_C = 4137,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_GETHITSEQ_S", Value=4138)]
      FIGHT_GETHITSEQ_S = 4138,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_YAMI_HITDOWN_S", Value=4139)]
      FIGHT_YAMI_HITDOWN_S = 4139,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_WAITRESULT_AG_C", Value=4140)]
      FIGHT_WAITRESULT_AG_C = 4140,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_WAITRESULT_AG_S", Value=4141)]
      FIGHT_WAITRESULT_AG_S = 4141,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_CMD", Value=4352)]
      CHAT_CMD = 4352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PRIVATE_REQ", Value=4353)]
      CHAT_PRIVATE_REQ = 4353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_WORLD_REQ", Value=4354)]
      CHAT_WORLD_REQ = 4354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_WORLD_RET", Value=4355)]
      CHAT_WORLD_RET = 4355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_CITY_REQ", Value=4356)]
      CHAT_CITY_REQ = 4356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_CITY_RET", Value=4357)]
      CHAT_CITY_RET = 4357,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_SOCIATY_REQ", Value=4358)]
      CHAT_SOCIATY_REQ = 4358,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_SOCIATY_RET", Value=4359)]
      CHAT_SOCIATY_RET = 4359,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_INVITEPK_REQ", Value=4360)]
      CHAT_INVITEPK_REQ = 4360,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_INVITEPK_RET", Value=4361)]
      CHAT_INVITEPK_RET = 4361,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_SPEAKER_REQ", Value=4362)]
      BUY_SPEAKER_REQ = 4362,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_SPEAKER_RET", Value=4363)]
      BUY_SPEAKER_RET = 4363,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_CMD", Value=4608)]
      SOUL_CMD = 4608,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_SOUL_LIST", Value=4609)]
      SEND_SOUL_LIST = 4609,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_EQUIP_REQ", Value=4612)]
      SOUL_EQUIP_REQ = 4612,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_EQUIP_RET", Value=4613)]
      SOUL_EQUIP_RET = 4613,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_MERGE_REQ", Value=4614)]
      SOUL_MERGE_REQ = 4614,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_MERGE_RET", Value=4615)]
      SOUL_MERGE_RET = 4615,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_EVOLUT_REQ", Value=4616)]
      SOUL_EVOLUT_REQ = 4616,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_EVOLUT_RET", Value=4617)]
      SOUL_EVOLUT_RET = 4617,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW_SOUL_LIST", Value=4618)]
      NEW_SOUL_LIST = 4618,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_UPGRADE_REQ", Value=4619)]
      SOUL_UPGRADE_REQ = 4619,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_UPGRADE_RET", Value=4620)]
      SOUL_UPGRADE_RET = 4620,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_DUST_BUY_REQ", Value=4621)]
      SOUL_DUST_BUY_REQ = 4621,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_DUST_BUY_RET", Value=4622)]
      SOUL_DUST_BUY_RET = 4622,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_DECOMPOSE_REQ", Value=4623)]
      SOUL_DECOMPOSE_REQ = 4623,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_DECOMPOSE_RET", Value=4610)]
      SOUL_DECOMPOSE_RET = 4610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_INFO_REQ", Value=4624)]
      SOULFIGHT_INFO_REQ = 4624,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_INFO_RET", Value=4625)]
      SOULFIGHT_INFO_RET = 4625,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_REFRESH_REQ", Value=4626)]
      SOULFIGHT_REFRESH_REQ = 4626,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_REFRESH_RET", Value=4627)]
      SOULFIGHT_REFRESH_RET = 4627,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_DRAW_REQ", Value=4628)]
      SOULFIGHT_DRAW_REQ = 4628,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_DRAW_RET", Value=4629)]
      SOULFIGHT_DRAW_RET = 4629,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_BEGIN_REQ", Value=4630)]
      SOULFIGHT_BEGIN_REQ = 4630,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_BEGIN_RET", Value=4631)]
      SOULFIGHT_BEGIN_RET = 4631,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_EQUIP_BLADE_REQ", Value=4632)]
      SOULFIGHT_EQUIP_BLADE_REQ = 4632,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_EQUIP_BLADE_RET", Value=4633)]
      SOULFIGHT_EQUIP_BLADE_RET = 4633,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_BLADE_SP_RET", Value=4634)]
      SOULFIGHT_BLADE_SP_RET = 4634,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_GET_DRAW_REQ", Value=4635)]
      SOULFIGHT_GET_DRAW_REQ = 4635,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULFIGHT_GET_DRAW_RET", Value=4636)]
      SOULFIGHT_GET_DRAW_RET = 4636,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_CMD", Value=4864)]
      ARENA_CMD = 4864,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_INFO_REQ", Value=4865)]
      ARENA_INFO_REQ = 4865,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_INFO_RET", Value=4866)]
      ARENA_INFO_RET = 4866,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_RANDOM_ROLE_REQ", Value=4867)]
      ARENA_RANDOM_ROLE_REQ = 4867,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_RANDOM_ROLE_RET", Value=4868)]
      ARENA_RANDOM_ROLE_RET = 4868,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_FIGHT_REQ", Value=4869)]
      ARENA_FIGHT_REQ = 4869,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_BUY_TIMES_REQ", Value=4871)]
      ARENA_BUY_TIMES_REQ = 4871,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_BUY_TIMES_RET", Value=4872)]
      ARENA_BUY_TIMES_RET = 4872,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_CLEAR_CD_REQ", Value=4873)]
      ARENA_CLEAR_CD_REQ = 4873,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_CLEAR_CD_RET", Value=4874)]
      ARENA_CLEAR_CD_RET = 4874,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_GIVE_UP_MATCHED", Value=4881)]
      ARENA_GIVE_UP_MATCHED = 4881,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_RANK_NTF", Value=4882)]
      ARENA_RANK_NTF = 4882,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_RECORDS_REQ", Value=4883)]
      ARENA_RECORDS_REQ = 4883,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_RECORDS_RET", Value=4884)]
      ARENA_RECORDS_RET = 4884,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_GET_BP_REQ", Value=4885)]
      ARENA_GET_BP_REQ = 4885,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_GET_BP_RET", Value=4886)]
      ARENA_GET_BP_RET = 4886,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRAINING_CMD", Value=5120)]
      TRAINING_CMD = 5120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMANDPHONE_INFO_REQ", Value=5121)]
      COMMANDPHONE_INFO_REQ = 5121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMANDPHONE_INFO_RSP", Value=5122)]
      COMMANDPHONE_INFO_RSP = 5122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_COMMANDPHONE_REQ", Value=5123)]
      ENTER_COMMANDPHONE_REQ = 5123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULROOM_INFO_REQ", Value=5124)]
      SOULROOM_INFO_REQ = 5124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULROOM_INFO_RSP", Value=5125)]
      SOULROOM_INFO_RSP = 5125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_SOULROOM_REQ", Value=5126)]
      ENTER_SOULROOM_REQ = 5126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULROOM_BUYTIMES_REQ", Value=5127)]
      SOULROOM_BUYTIMES_REQ = 5127,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULROOM_BUYTIMES_RET", Value=5128)]
      SOULROOM_BUYTIMES_RET = 5128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_CMD", Value=5376)]
      GACHA_CMD = 5376,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_INFO_REQ", Value=5377)]
      GACHA_INFO_REQ = 5377,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_INFO_RET", Value=5378)]
      GACHA_INFO_RET = 5378,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_EXEC_REQ", Value=5379)]
      GACHA_EXEC_REQ = 5379,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_EXEC_RET", Value=5380)]
      GACHA_EXEC_RET = 5380,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_CMD", Value=5632)]
      SHOP_CMD = 5632,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_INFO_REQ", Value=5633)]
      SHOP_INFO_REQ = 5633,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_INFO_RET", Value=5634)]
      SHOP_INFO_RET = 5634,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_BUY_ITEM_REQ", Value=5635)]
      SHOP_BUY_ITEM_REQ = 5635,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_BUY_ITEM_RET", Value=5636)]
      SHOP_BUY_ITEM_RET = 5636,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_REFRESH_REQ", Value=5637)]
      SHOP_REFRESH_REQ = 5637,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_REFRESH_RET", Value=5638)]
      SHOP_REFRESH_RET = 5638,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_CMD", Value=5888)]
      RANK_CMD = 5888,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_INFO_REQ", Value=5889)]
      RANK_INFO_REQ = 5889,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_INFO_RET", Value=5890)]
      RANK_INFO_RET = 5890,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_CMD", Value=6144)]
      ACTIVITY_CMD = 6144,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_INFO_REQ", Value=6145)]
      ACTIVITY_INFO_REQ = 6145,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_INFO_RET", Value=6146)]
      ACTIVITY_INFO_RET = 6146,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_SIGN_REQ", Value=6147)]
      DAILY_SIGN_REQ = 6147,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_SIGN_RET", Value=6148)]
      DAILY_SIGN_RET = 6148,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPA_REQ", Value=6149)]
      SPA_REQ = 6149,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPA_RET", Value=6150)]
      SPA_RET = 6150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONTHCARD_BUY_REQ", Value=6151)]
      MONTHCARD_BUY_REQ = 6151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONTHCARD_BUY_RET", Value=6152)]
      MONTHCARD_BUY_RET = 6152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONTHCARD_REWARD_REQ", Value=6153)]
      MONTHCARD_REWARD_REQ = 6153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONTHCARD_REWARD_RET", Value=6160)]
      MONTHCARD_REWARD_RET = 6160,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOSS_CMD", Value=6400)]
      BOSS_CMD = 6400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOSS_INFO_REQ", Value=6401)]
      BOSS_INFO_REQ = 6401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GLOBAL_BOSS_INFO_RET", Value=6402)]
      GLOBAL_BOSS_INFO_RET = 6402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_BOSS_INFO_RET", Value=6403)]
      ROLE_BOSS_INFO_RET = 6403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOSS_INSPIRE_REQ", Value=6406)]
      BOSS_INSPIRE_REQ = 6406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOSS_INSPIRE_RET", Value=6407)]
      BOSS_INSPIRE_RET = 6407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_BOSS_REQ", Value=6408)]
      START_BOSS_REQ = 6408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_BOSS_RET", Value=6409)]
      START_BOSS_RET = 6409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHALLENGE_BOSS_REQ", Value=6410)]
      CHALLENGE_BOSS_REQ = 6410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUB_HP_TOP_LIST_NTF", Value=6411)]
      SUB_HP_TOP_LIST_NTF = 6411
    }
  
}