//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mailtype.proto
// Note: requires additional types generated from: itemtype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SysMailConf")]
  public partial class SysMailConf : global::ProtoBuf.IExtensible
  {
    public SysMailConf() {}
    
    private string _sender = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _text = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ItemNotiType> _item = new global::System.Collections.Generic.List<Cmd.ItemNotiType>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ItemNotiType> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailInfo")]
  public partial class MailInfo : global::ProtoBuf.IExtensible
  {
    public MailInfo() {}
    
    private ulong _thisid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _mailid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _createTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private uint _validity;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"validity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint validity
    {
      get { return _validity; }
      set { _validity = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private Cmd.SysMailConf _content = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.SysMailConf content
    {
      get { return _content; }
      set { _content = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _arg = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> arg
    {
      get { return _arg; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}