//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: arena.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: arenatype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaInfoReq")]
  public partial class ArenaInfoReq : global::ProtoBuf.IExtensible
  {
    public ArenaInfoReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_INFO_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_INFO_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaInfoRet")]
  public partial class ArenaInfoRet : global::ProtoBuf.IExtensible
  {
    public ArenaInfoRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_INFO_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_INFO_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Cmd.ArenaInfo _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.ArenaInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRankNtf")]
  public partial class ArenaRankNtf : global::ProtoBuf.IExtensible
  {
    public ArenaRankNtf() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_RANK_NTF;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_RANK_NTF)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRandomRoleReq")]
  public partial class ArenaRandomRoleReq : global::ProtoBuf.IExtensible
  {
    public ArenaRandomRoleReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_RANDOM_ROLE_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_RANDOM_ROLE_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRandomRoleRet")]
  public partial class ArenaRandomRoleRet : global::ProtoBuf.IExtensible
  {
    public ArenaRandomRoleRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_RANDOM_ROLE_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_RANDOM_ROLE_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ArenaRoleInfo> _list = new global::System.Collections.Generic.List<Cmd.ArenaRoleInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ArenaRoleInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaFightReq")]
  public partial class ArenaFightReq : global::ProtoBuf.IExtensible
  {
    public ArenaFightReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_FIGHT_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_FIGHT_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _roleid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaBuyTimesReq")]
  public partial class ArenaBuyTimesReq : global::ProtoBuf.IExtensible
  {
    public ArenaBuyTimesReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_BUY_TIMES_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_BUY_TIMES_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaBuyTimesRet")]
  public partial class ArenaBuyTimesRet : global::ProtoBuf.IExtensible
  {
    public ArenaBuyTimesRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_BUY_TIMES_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_BUY_TIMES_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _lastbuytime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastbuytime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastbuytime
    {
      get { return _lastbuytime; }
      set { _lastbuytime = value; }
    }
    private uint _daybuytimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"daybuytimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint daybuytimes
    {
      get { return _daybuytimes; }
      set { _daybuytimes = value; }
    }
    private uint _unusedbuytimes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"unusedbuytimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unusedbuytimes
    {
      get { return _unusedbuytimes; }
      set { _unusedbuytimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaClearCDReq")]
  public partial class ArenaClearCDReq : global::ProtoBuf.IExtensible
  {
    public ArenaClearCDReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_CLEAR_CD_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_CLEAR_CD_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaClearCDRet")]
  public partial class ArenaClearCDRet : global::ProtoBuf.IExtensible
  {
    public ArenaClearCDRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_CLEAR_CD_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_CLEAR_CD_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaGiveUpMatched")]
  public partial class ArenaGiveUpMatched : global::ProtoBuf.IExtensible
  {
    public ArenaGiveUpMatched() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_GIVE_UP_MATCHED;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_GIVE_UP_MATCHED)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRecordsReq")]
  public partial class ArenaRecordsReq : global::ProtoBuf.IExtensible
  {
    public ArenaRecordsReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_RECORDS_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_RECORDS_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRecordsRet")]
  public partial class ArenaRecordsRet : global::ProtoBuf.IExtensible
  {
    public ArenaRecordsRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ARENA_RECORDS_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ARENA_RECORDS_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ArenaRecordInfo> _list = new global::System.Collections.Generic.List<Cmd.ArenaRecordInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ArenaRecordInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}