//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: bladetype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewBlade")]
  public partial class NewBlade : global::ProtoBuf.IExtensible
  {
    public NewBlade() {}
    
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _equipindex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint equipindex
    {
      get { return _equipindex; }
      set { _equipindex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeInfo")]
  public partial class BladeInfo : global::ProtoBuf.IExtensible
  {
    public BladeInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _quality;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private uint _strengthlv;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"strengthlv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint strengthlv
    {
      get { return _strengthlv; }
      set { _strengthlv = value; }
    }
    private uint _releaselv;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"releaselv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint releaselv
    {
      get { return _releaselv; }
      set { _releaselv = value; }
    }
    private uint _equipindex;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint equipindex
    {
      get { return _equipindex; }
      set { _equipindex = value; }
    }
    private ulong _liberation;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"liberation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong liberation
    {
      get { return _liberation; }
      set { _liberation = value; }
    }
    private uint _skillid1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"skillid1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid1
    {
      get { return _skillid1; }
      set { _skillid1 = value; }
    }
    private uint _skilllv1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"skilllv1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skilllv1
    {
      get { return _skilllv1; }
      set { _skilllv1 = value; }
    }
    private uint _skillid2;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"skillid2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid2
    {
      get { return _skillid2; }
      set { _skillid2 = value; }
    }
    private uint _skilllv2;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"skilllv2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skilllv2
    {
      get { return _skilllv2; }
      set { _skilllv2 = value; }
    }
    private uint _skillid3;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"skillid3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid3
    {
      get { return _skillid3; }
      set { _skillid3 = value; }
    }
    private uint _skilllv3;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"skilllv3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skilllv3
    {
      get { return _skilllv3; }
      set { _skilllv3 = value; }
    }
    private uint _soulfightsp = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"soulfightsp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint soulfightsp
    {
      get { return _soulfightsp; }
      set { _soulfightsp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}