//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: blade.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: bladetype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendBladeList")]
  public partial class SendBladeList : global::ProtoBuf.IExtensible
  {
    public SendBladeList() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SEND_BLADE_LIST;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SEND_BLADE_LIST)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.BladeInfo> _list = new global::System.Collections.Generic.List<Cmd.BladeInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.BladeInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeStrengthReq")]
  public partial class BladeStrengthReq : global::ProtoBuf.IExtensible
  {
    public BladeStrengthReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_STRENGTH_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_STRENGTH_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeStrengthRet")]
  public partial class BladeStrengthRet : global::ProtoBuf.IExtensible
  {
    public BladeStrengthRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_STRENGTH_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_STRENGTH_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _quality;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private uint _strengthlv;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"strengthlv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint strengthlv
    {
      get { return _strengthlv; }
      set { _strengthlv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeBreakReq")]
  public partial class BladeBreakReq : global::ProtoBuf.IExtensible
  {
    public BladeBreakReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_BREAK_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_BREAK_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeBreakRet")]
  public partial class BladeBreakRet : global::ProtoBuf.IExtensible
  {
    public BladeBreakRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_BREAK_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_BREAK_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeExchangeReq")]
  public partial class BladeExchangeReq : global::ProtoBuf.IExtensible
  {
    public BladeExchangeReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_EXCHANGE_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_EXCHANGE_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _srcindex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"srcindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint srcindex
    {
      get { return _srcindex; }
      set { _srcindex = value; }
    }
    private uint _dstid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dstid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dstid
    {
      get { return _dstid; }
      set { _dstid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeExchangeRet")]
  public partial class BladeExchangeRet : global::ProtoBuf.IExtensible
  {
    public BladeExchangeRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_EXCHANGE_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_EXCHANGE_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _srcid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"srcid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint srcid
    {
      get { return _srcid; }
      set { _srcid = value; }
    }
    private uint _srcindex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"srcindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint srcindex
    {
      get { return _srcindex; }
      set { _srcindex = value; }
    }
    private uint _dstid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"dstid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dstid
    {
      get { return _dstid; }
      set { _dstid = value; }
    }
    private uint _dstindex;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dstindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dstindex
    {
      get { return _dstindex; }
      set { _dstindex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeLotteryReq")]
  public partial class BladeLotteryReq : global::ProtoBuf.IExtensible
  {
    public BladeLotteryReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_LOTTERY_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_LOTTERY_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeLotteryRet")]
  public partial class BladeLotteryRet : global::ProtoBuf.IExtensible
  {
    public BladeLotteryRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_LOTTERY_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_LOTTERY_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillUpgradeReq")]
  public partial class SkillUpgradeReq : global::ProtoBuf.IExtensible
  {
    public SkillUpgradeReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SKILL_UPGRADE_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SKILL_UPGRADE_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private uint _times;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillUpgradeRet")]
  public partial class SkillUpgradeRet : global::ProtoBuf.IExtensible
  {
    public SkillUpgradeRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SKILL_UPGRADE_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SKILL_UPGRADE_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private uint _skilllevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"skilllevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skilllevel
    {
      get { return _skilllevel; }
      set { _skilllevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewBladeList")]
  public partial class NewBladeList : global::ProtoBuf.IExtensible
  {
    public NewBladeList() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.NEW_BLADE_LIST;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.NEW_BLADE_LIST)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.NewBlade> _bladelist = new global::System.Collections.Generic.List<Cmd.NewBlade>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bladelist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.NewBlade> bladelist
    {
      get { return _bladelist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeLiberationReq")]
  public partial class BladeLiberationReq : global::ProtoBuf.IExtensible
  {
    public BladeLiberationReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_LIBERATION_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_LIBERATION_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _nodeid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nodeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint nodeid
    {
      get { return _nodeid; }
      set { _nodeid = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeLiberationRet")]
  public partial class BladeLiberationRet : global::ProtoBuf.IExtensible
  {
    public BladeLiberationRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BLADE_LIBERATION_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BLADE_LIBERATION_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _nodeid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nodeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint nodeid
    {
      get { return _nodeid; }
      set { _nodeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}