//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: boss.proto
// Note: requires additional types generated from: basetype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BossInfoReq")]
  public partial class BossInfoReq : global::ProtoBuf.IExtensible
  {
    public BossInfoReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BOSS_INFO_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BOSS_INFO_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GlobalBossInfoRet")]
  public partial class GlobalBossInfoRet : global::ProtoBuf.IExtensible
  {
    public GlobalBossInfoRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.GLOBAL_BOSS_INFO_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.GLOBAL_BOSS_INFO_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _yammythisid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yammythisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong yammythisid
    {
      get { return _yammythisid; }
      set { _yammythisid = value; }
    }
    private uint _yammyresult;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"yammyresult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint yammyresult
    {
      get { return _yammyresult; }
      set { _yammyresult = value; }
    }
    private ulong _kenseithisid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"kenseithisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong kenseithisid
    {
      get { return _kenseithisid; }
      set { _kenseithisid = value; }
    }
    private uint _kenseitime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"kenseitime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint kenseitime
    {
      get { return _kenseitime; }
      set { _kenseitime = value; }
    }
    private ulong _kenseiowner;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"kenseiowner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong kenseiowner
    {
      get { return _kenseiowner; }
      set { _kenseiowner = value; }
    }
    private uint _kenseijoined;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"kenseijoined", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint kenseijoined
    {
      get { return _kenseijoined; }
      set { _kenseijoined = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleBossInfoRet")]
  public partial class RoleBossInfoRet : global::ProtoBuf.IExtensible
  {
    public RoleBossInfoRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ROLE_BOSS_INFO_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ROLE_BOSS_INFO_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _lastbuytime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastbuytime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastbuytime
    {
      get { return _lastbuytime; }
      set { _lastbuytime = value; }
    }
    private uint _buytimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"buytimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint buytimes
    {
      get { return _buytimes; }
      set { _buytimes = value; }
    }
    private uint _jointimes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"jointimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint jointimes
    {
      get { return _jointimes; }
      set { _jointimes = value; }
    }
    private ulong _pigmanthisid;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pigmanthisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong pigmanthisid
    {
      get { return _pigmanthisid; }
      set { _pigmanthisid = value; }
    }
    private uint _lasttime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"lasttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lasttime
    {
      get { return _lasttime; }
      set { _lasttime = value; }
    }
    private uint _usedtimes;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"usedtimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint usedtimes
    {
      get { return _usedtimes; }
      set { _usedtimes = value; }
    }
    private ulong _inspire1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"inspire1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong inspire1
    {
      get { return _inspire1; }
      set { _inspire1 = value; }
    }
    private ulong _inspire2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"inspire2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong inspire2
    {
      get { return _inspire2; }
      set { _inspire2 = value; }
    }
    private ulong _inspire3;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"inspire3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong inspire3
    {
      get { return _inspire3; }
      set { _inspire3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BossInspireReq")]
  public partial class BossInspireReq : global::ProtoBuf.IExtensible
  {
    public BossInspireReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BOSS_INSPIRE_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BOSS_INSPIRE_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bossid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bossid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bossid
    {
      get { return _bossid; }
      set { _bossid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BossInspireRet")]
  public partial class BossInspireRet : global::ProtoBuf.IExtensible
  {
    public BossInspireRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.BOSS_INSPIRE_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.BOSS_INSPIRE_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bossid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bossid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bossid
    {
      get { return _bossid; }
      set { _bossid = value; }
    }
    private ulong _inspire;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"inspire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong inspire
    {
      get { return _inspire; }
      set { _inspire = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartBossReq")]
  public partial class StartBossReq : global::ProtoBuf.IExtensible
  {
    public StartBossReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.START_BOSS_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.START_BOSS_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartBossRet")]
  public partial class StartBossRet : global::ProtoBuf.IExtensible
  {
    public StartBossRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.START_BOSS_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.START_BOSS_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _starttime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"starttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint starttime
    {
      get { return _starttime; }
      set { _starttime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeBossReq")]
  public partial class ChallengeBossReq : global::ProtoBuf.IExtensible
  {
    public ChallengeBossReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.CHALLENGE_BOSS_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.CHALLENGE_BOSS_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bossid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bossid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bossid
    {
      get { return _bossid; }
      set { _bossid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleHPInfo")]
  public partial class RoleHPInfo : global::ProtoBuf.IExtensible
  {
    public RoleHPInfo() {}
    
    private ulong _roleid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private byte[] _rolename;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rolename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] rolename
    {
      get { return _rolename; }
      set { _rolename = value; }
    }
    private uint _totalhp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"totalhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint totalhp
    {
      get { return _totalhp; }
      set { _totalhp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubHPTopListNtf")]
  public partial class SubHPTopListNtf : global::ProtoBuf.IExtensible
  {
    public SubHPTopListNtf() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SUB_HP_TOP_LIST_NTF;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SUB_HP_TOP_LIST_NTF)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _bossid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bossid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bossid
    {
      get { return _bossid; }
      set { _bossid = value; }
    }
    private uint _bosshp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bosshp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bosshp
    {
      get { return _bosshp; }
      set { _bosshp = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.RoleHPInfo> _list = new global::System.Collections.Generic.List<Cmd.RoleHPInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.RoleHPInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}