//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: errorcode.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyVersion")]
  public partial class VerifyVersion : global::ProtoBuf.IExtensible
  {
    public VerifyVersion() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.VERIFY_VERSION;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.VERIFY_VERSION)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _clientversion;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"clientversion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint clientversion
    {
      get { return _clientversion; }
      set { _clientversion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TempCredentialReq")]
  public partial class TempCredentialReq : global::ProtoBuf.IExtensible
  {
    public TempCredentialReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.TEMP_CREDENTIAL_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.TEMP_CREDENTIAL_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TempCredentialRet")]
  public partial class TempCredentialRet : global::ProtoBuf.IExtensible
  {
    public TempCredentialRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.TEMP_CREDENTIAL_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.TEMP_CREDENTIAL_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _tempcredential;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tempcredential", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tempcredential
    {
      get { return _tempcredential; }
      set { _tempcredential = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.LOGIN_LOGIN_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.LOGIN_LOGIN_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _accountid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong accountid
    {
      get { return _accountid; }
      set { _accountid = value; }
    }
    private string _verifier = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"verifier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string verifier
    {
      get { return _verifier; }
      set { _verifier = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRet")]
  public partial class LoginRet : global::ProtoBuf.IExtensible
  {
    public LoginRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.LOGIN_LOGIN_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.LOGIN_LOGIN_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _accountid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accountid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong accountid
    {
      get { return _accountid; }
      set { _accountid = value; }
    }
    private uint _token = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _gatewayip = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gatewayip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gatewayip
    {
      get { return _gatewayip; }
      set { _gatewayip = value; }
    }
    private uint _gatewayport = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gatewayport", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gatewayport
    {
      get { return _gatewayport; }
      set { _gatewayport = value; }
    }
    private string _transitip = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"transitip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string transitip
    {
      get { return _transitip; }
      set { _transitip = value; }
    }
    private uint _transitport = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"transitport", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint transitport
    {
      get { return _transitport; }
      set { _transitport = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginGatewayReq")]
  public partial class LoginGatewayReq : global::ProtoBuf.IExtensible
  {
    public LoginGatewayReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.LOGIN_GATEW_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.LOGIN_GATEW_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _accountid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong accountid
    {
      get { return _accountid; }
      set { _accountid = value; }
    }
    private uint _token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _appVersion = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"appVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string appVersion
    {
      get { return _appVersion; }
      set { _appVersion = value; }
    }
    private uint _deviceId = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deviceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint deviceId
    {
      get { return _deviceId; }
      set { _deviceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginGatewayRet")]
  public partial class LoginGatewayRet : global::ProtoBuf.IExtensible
  {
    public LoginGatewayRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.LOGIN_GATEW_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.LOGIN_GATEW_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginTransitReq")]
  public partial class LoginTransitReq : global::ProtoBuf.IExtensible
  {
    public LoginTransitReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.LOGIN_TRANSIT_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.LOGIN_TRANSIT_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _roleid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private ulong _accountid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accountid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong accountid
    {
      get { return _accountid; }
      set { _accountid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginTransitRet")]
  public partial class LoginTransitRet : global::ProtoBuf.IExtensible
  {
    public LoginTransitRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.LOGIN_TRANSIT_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.LOGIN_TRANSIT_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}