//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: masktype.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"EMask")]
    public enum EMask
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_OPENED", Value=1)]
      GACHA_OPENED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_OPENED", Value=2)]
      BLADE_OPENED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLADE_STRENGTH_OPENED", Value=3)]
      BLADE_STRENGTH_OPENED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_OPENED", Value=4)]
      ROLE_OPENED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_OPENED", Value=5)]
      SOUL_OPENED = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_UPGRADE_OPENED", Value=6)]
      SOUL_UPGRADE_OPENED = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_OPENED", Value=7)]
      SHOP_OPENED = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_ROOM_OPENED", Value=8)]
      SOUL_ROOM_OPENED = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_MACHINE_OPENED", Value=9)]
      GOLD_MACHINE_OPENED = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_REG_OPENED", Value=10)]
      DAILY_REG_OPENED = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIGH_PVE_OPENED", Value=11)]
      HIGH_PVE_OPENED = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_OPENED", Value=12)]
      ARENA_OPENED = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PHONE_OPENED", Value=13)]
      CMD_PHONE_OPENED = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCK_KONT_OPENED", Value=14)]
      LOCK_KONT_OPENED = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUL_FIGHT_OPENED", Value=15)]
      SOUL_FIGHT_OPENED = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIBERATION_OPENED", Value=16)]
      LIBERATION_OPENED = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRAINING_OPENED", Value=17)]
      TRAINING_OPENED = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOSS_OPENED", Value=18)]
      BOSS_OPENED = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOWER_OPENED", Value=19)]
      TOWER_OPENED = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_OPENED", Value=20)]
      RANK_OPENED = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULCORE_OPENED", Value=21)]
      SOULCORE_OPENED = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLESQUARE_OPENED", Value=22)]
      BATTLESQUARE_OPENED = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREE_REWARD_OPENED", Value=23)]
      FREE_REWARD_OPENED = 23
    }
  
}