//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: quest.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: questtype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetQuestList")]
  public partial class MessageGetQuestList : global::ProtoBuf.IExtensible
  {
    public MessageGetQuestList() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.GET_QUESTLIST_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.GET_QUESTLIST_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageQuestList")]
  public partial class MessageQuestList : global::ProtoBuf.IExtensible
  {
    public MessageQuestList() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.GET_QUESTLIST_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.GET_QUESTLIST_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _showids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"showids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> showids
    {
      get { return _showids; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _acceptids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"acceptids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> acceptids
    {
      get { return _acceptids; }
    }
  
    private readonly global::System.Collections.Generic.List<Cmd.QuestInfoBase> _doings = new global::System.Collections.Generic.List<Cmd.QuestInfoBase>();
    [global::ProtoBuf.ProtoMember(4, Name=@"doings", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.QuestInfoBase> doings
    {
      get { return _doings; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGetDailyQuestList")]
  public partial class MessageGetDailyQuestList : global::ProtoBuf.IExtensible
  {
    public MessageGetDailyQuestList() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.GET_DAILYQUEST_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.GET_DAILYQUEST_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageDailyQuestList")]
  public partial class MessageDailyQuestList : global::ProtoBuf.IExtensible
  {
    public MessageDailyQuestList() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.GET_DAILYQUEST_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.GET_DAILYQUEST_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.QuestInfoBase> _lists = new global::System.Collections.Generic.List<Cmd.QuestInfoBase>();
    [global::ProtoBuf.ProtoMember(3, Name=@"lists", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.QuestInfoBase> lists
    {
      get { return _lists; }
    }
  
    private uint _nowtime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nowtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint nowtime
    {
      get { return _nowtime; }
      set { _nowtime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageAcceptQuestRequest")]
  public partial class MessageAcceptQuestRequest : global::ProtoBuf.IExtensible
  {
    public MessageAcceptQuestRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ACCEPT_QUEST_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ACCEPT_QUEST_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _questid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageAcceptQuestResponse")]
  public partial class MessageAcceptQuestResponse : global::ProtoBuf.IExtensible
  {
    public MessageAcceptQuestResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.ACCEPT_QUEST_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.ACCEPT_QUEST_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _questid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private Cmd.QuestInfoBase _progress;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.QuestInfoBase progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageSubmitQuestRequest")]
  public partial class MessageSubmitQuestRequest : global::ProtoBuf.IExtensible
  {
    public MessageSubmitQuestRequest() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SUBMIT_QUEST_C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SUBMIT_QUEST_C)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _questid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageSubmitQuestResponse")]
  public partial class MessageSubmitQuestResponse : global::ProtoBuf.IExtensible
  {
    public MessageSubmitQuestResponse() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.SUBMIT_QUEST_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.SUBMIT_QUEST_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _questid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.QuestResourceReward> _resource = new global::System.Collections.Generic.List<Cmd.QuestResourceReward>();
    [global::ProtoBuf.ProtoMember(3, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.QuestResourceReward> resource
    {
      get { return _resource; }
    }
  
    private readonly global::System.Collections.Generic.List<Cmd.QuestItemReward> _items = new global::System.Collections.Generic.List<Cmd.QuestItemReward>();
    [global::ProtoBuf.ProtoMember(4, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.QuestItemReward> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageQuestProgressNotice")]
  public partial class MessageQuestProgressNotice : global::ProtoBuf.IExtensible
  {
    public MessageQuestProgressNotice() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.QUEST_PROGRESS_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.QUEST_PROGRESS_S)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Cmd.QuestInfoBase _progress = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.QuestInfoBase progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}