//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: scenetype.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: roletype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SceneUnitInfo")]
  public partial class SceneUnitInfo : global::ProtoBuf.IExtensible
  {
    public SceneUnitInfo() {}
    
    private ulong _unitid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong unitid
    {
      get { return _unitid; }
      set { _unitid = value; }
    }
    private byte[] _rolename = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rolename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] rolename
    {
      get { return _rolename; }
      set { _rolename = value; }
    }
    private Cmd.RoleAvatar _avatar = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.RoleAvatar avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private int _pos_x = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightSword")]
  public partial class FightSword : global::ProtoBuf.IExtensible
  {
    public FightSword() {}
    
    private int _swordid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"swordid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int swordid
    {
      get { return _swordid; }
      set { _swordid = value; }
    }
    private int _cp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cp
    {
      get { return _cp; }
      set { _cp = value; }
    }
    private int _maxcp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxcp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxcp
    {
      get { return _maxcp; }
      set { _maxcp = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.FightSpell> _spells = new global::System.Collections.Generic.List<Cmd.FightSpell>();
    [global::ProtoBuf.ProtoMember(5, Name=@"spells", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.FightSpell> spells
    {
      get { return _spells; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightSpell")]
  public partial class FightSpell : global::ProtoBuf.IExtensible
  {
    public FightSpell() {}
    
    private int _spellid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"spellid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spellid
    {
      get { return _spellid; }
      set { _spellid = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _dam = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dam
    {
      get { return _dam; }
      set { _dam = value; }
    }
    private int _exhpdam = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exhpdam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exhpdam
    {
      get { return _exhpdam; }
      set { _exhpdam = value; }
    }
    private int _excpdam = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"excpdam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int excpdam
    {
      get { return _excpdam; }
      set { _excpdam = value; }
    }
    private int _cdtime = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cdtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cdtime
    {
      get { return _cdtime; }
      set { _cdtime = value; }
    }
    private int _cpcost = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cpcost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cpcost
    {
      get { return _cpcost; }
      set { _cpcost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightFactor")]
  public partial class FightFactor : global::ProtoBuf.IExtensible
  {
    public FightFactor() {}
    
    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _phy = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"phy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int phy
    {
      get { return _phy; }
      set { _phy = value; }
    }
    private int _str = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"str", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int str
    {
      get { return _str; }
      set { _str = value; }
    }
    private int _inte = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"inte", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int inte
    {
      get { return _inte; }
      set { _inte = value; }
    }
    private int _spi = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"spi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spi
    {
      get { return _spi; }
      set { _spi = value; }
    }
    private int _maxhp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxhp
    {
      get { return _maxhp; }
      set { _maxhp = value; }
    }
    private int _cprev = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cprev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cprev
    {
      get { return _cprev; }
      set { _cprev = value; }
    }
    private int _mp = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private int _patt = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"patt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int patt
    {
      get { return _patt; }
      set { _patt = value; }
    }
    private int _pdef = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pdef
    {
      get { return _pdef; }
      set { _pdef = value; }
    }
    private int _catt = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"catt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int catt
    {
      get { return _catt; }
      set { _catt = value; }
    }
    private int _cdef = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"cdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cdef
    {
      get { return _cdef; }
      set { _cdef = value; }
    }
    private int _cp = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"cp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cp
    {
      get { return _cp; }
      set { _cp = value; }
    }
    private int _hitrate = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hitrate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hitrate
    {
      get { return _hitrate; }
      set { _hitrate = value; }
    }
    private int _dodgerate = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"dodgerate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dodgerate
    {
      get { return _dodgerate; }
      set { _dodgerate = value; }
    }
    private int _crit = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int crit
    {
      get { return _crit; }
      set { _crit = value; }
    }
    private int _tenacity = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"tenacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tenacity
    {
      get { return _tenacity; }
      set { _tenacity = value; }
    }
    private int _critmultiple = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"critmultiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int critmultiple
    {
      get { return _critmultiple; }
      set { _critmultiple = value; }
    }
    private int _critdecr = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"critdecr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int critdecr
    {
      get { return _critdecr; }
      set { _critdecr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightSoldier")]
  public partial class FightSoldier : global::ProtoBuf.IExtensible
  {
    public FightSoldier() {}
    
    private ulong _unitid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong unitid
    {
      get { return _unitid; }
      set { _unitid = value; }
    }
    private int _soldier = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"soldier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int soldier
    {
      get { return _soldier; }
      set { _soldier = value; }
    }
    private Cmd.FightFactor _factor = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"factor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.FightFactor factor
    {
      get { return _factor; }
      set { _factor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyRewards")]
  public partial class CopyRewards : global::ProtoBuf.IExtensible
  {
    public CopyRewards() {}
    
    private int _key = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyUnitInfo")]
  public partial class CopyUnitInfo : global::ProtoBuf.IExtensible
  {
    public CopyUnitInfo() {}
    
    private ulong _unitid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong unitid
    {
      get { return _unitid; }
      set { _unitid = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private byte[] _rolename = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rolename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] rolename
    {
      get { return _rolename; }
      set { _rolename = value; }
    }
    private int _soldier = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"soldier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int soldier
    {
      get { return _soldier; }
      set { _soldier = value; }
    }
    private Cmd.DressRetUnit _dress = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.DressRetUnit dress
    {
      get { return _dress; }
      set { _dress = value; }
    }
    private int _seed = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seed
    {
      get { return _seed; }
      set { _seed = value; }
    }
    private Cmd.FightFactor _factor = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"factor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.FightFactor factor
    {
      get { return _factor; }
      set { _factor = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.FightSoldier> _soldiers = new global::System.Collections.Generic.List<Cmd.FightSoldier>();
    [global::ProtoBuf.ProtoMember(8, Name=@"soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.FightSoldier> soldiers
    {
      get { return _soldiers; }
    }
  
    private readonly global::System.Collections.Generic.List<Cmd.FightSword> _swords = new global::System.Collections.Generic.List<Cmd.FightSword>();
    [global::ProtoBuf.ProtoMember(9, Name=@"swords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.FightSword> swords
    {
      get { return _swords; }
    }
  
    private readonly global::System.Collections.Generic.List<Cmd.CopyRewards> _rewards = new global::System.Collections.Generic.List<Cmd.CopyRewards>();
    [global::ProtoBuf.ProtoMember(10, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.CopyRewards> rewards
    {
      get { return _rewards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _soulbuff = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"soulbuff", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> soulbuff
    {
      get { return _soulbuff; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PkCopyUnitInfo")]
  public partial class PkCopyUnitInfo : global::ProtoBuf.IExtensible
  {
    public PkCopyUnitInfo() {}
    
    private ulong _unitid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong unitid
    {
      get { return _unitid; }
      set { _unitid = value; }
    }
    private byte[] _rolename = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rolename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] rolename
    {
      get { return _rolename; }
      set { _rolename = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private Cmd.DressRetUnit _dress = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.DressRetUnit dress
    {
      get { return _dress; }
      set { _dress = value; }
    }
    private Cmd.Avatar _avatar = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.Avatar avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyStatusInfo")]
  public partial class CopyStatusInfo : global::ProtoBuf.IExtensible
  {
    public CopyStatusInfo() {}
    
    private uint _copyid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _fighttimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fighttimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fighttimes
    {
      get { return _fighttimes; }
      set { _fighttimes = value; }
    }
    private uint _resettimes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"resettimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint resettimes
    {
      get { return _resettimes; }
      set { _resettimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopUnitInfo")]
  public partial class ShopUnitInfo : global::ProtoBuf.IExtensible
  {
    public ShopUnitInfo() {}
    
    private uint _shopid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shopid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint shopid
    {
      get { return _shopid; }
      set { _shopid = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SweepUnitInfo")]
  public partial class SweepUnitInfo : global::ProtoBuf.IExtensible
  {
    public SweepUnitInfo() {}
    
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _skillpoint = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skillpoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillpoint
    {
      get { return _skillpoint; }
      set { _skillpoint = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.CopyRewards> _rewards = new global::System.Collections.Generic.List<Cmd.CopyRewards>();
    [global::ProtoBuf.ProtoMember(5, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.CopyRewards> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotUnit")]
  public partial class RobotUnit : global::ProtoBuf.IExtensible
  {
    public RobotUnit() {}
    
    private ulong _roleid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private byte[] _rolename = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rolename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] rolename
    {
      get { return _rolename; }
      set { _rolename = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _vip = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private Cmd.Avatar _avatar = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.Avatar avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private uint _bladeid = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private Cmd.DressRetUnit _dress = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.DressRetUnit dress
    {
      get { return _dress; }
      set { _dress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleSquareInfo")]
  public partial class BattleSquareInfo : global::ProtoBuf.IExtensible
  {
    public BattleSquareInfo() {}
    
    private ulong _roleid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _score = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _isatk = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isatk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isatk
    {
      get { return _isatk; }
      set { _isatk = value; }
    }
    private uint _rank = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private uint _timestamp = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"FightMode")]
    public enum FightMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightMode_Single", Value=1)]
      eFightMode_Single = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightMode_Synchronization", Value=2)]
      eFightMode_Synchronization = 2
    }
  
}