//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: teamtype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamInfo")]
  public partial class TeamInfo : global::ProtoBuf.IExtensible
  {
    public TeamInfo() {}
    
    private uint _thisid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _leader;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"leader", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint leader
    {
      get { return _leader; }
      set { _leader = value; }
    }
    private uint _createTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private uint _serverid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"serverid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint serverid
    {
      get { return _serverid; }
      set { _serverid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}