//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: team.proto
// Note: requires additional types generated from: basetype.proto
// Note: requires additional types generated from: teamtype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateTeamReq")]
  public partial class CreateTeamReq : global::ProtoBuf.IExtensible
  {
    public CreateTeamReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.CREATE_TEAM_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.CREATE_TEAM_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teamtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teamtype
    {
      get { return _teamtype; }
      set { _teamtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateTeamRet")]
  public partial class CreateTeamRet : global::ProtoBuf.IExtensible
  {
    public CreateTeamRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.CREATE_TEAM_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.CREATE_TEAM_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teamid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teamid
    {
      get { return _teamid; }
      set { _teamid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteJoinTeamReq")]
  public partial class InviteJoinTeamReq : global::ProtoBuf.IExtensible
  {
    public InviteJoinTeamReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.INVITE_JOIN_TEAM_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.INVITE_JOIN_TEAM_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teamid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teamid
    {
      get { return _teamid; }
      set { _teamid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteJoinTeamRet")]
  public partial class InviteJoinTeamRet : global::ProtoBuf.IExtensible
  {
    public InviteJoinTeamRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.INVITE_JOIN_TEAM_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.INVITE_JOIN_TEAM_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinTeamReq")]
  public partial class JoinTeamReq : global::ProtoBuf.IExtensible
  {
    public JoinTeamReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.JOIN_TEAM_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.JOIN_TEAM_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teamid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teamid
    {
      get { return _teamid; }
      set { _teamid = value; }
    }
    private uint _serverid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"serverid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint serverid
    {
      get { return _serverid; }
      set { _serverid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinTeamRet")]
  public partial class JoinTeamRet : global::ProtoBuf.IExtensible
  {
    public JoinTeamRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.JOIN_TEAM_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.JOIN_TEAM_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teamid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teamid
    {
      get { return _teamid; }
      set { _teamid = value; }
    }
    private uint _leader;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"leader", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint leader
    {
      get { return _leader; }
      set { _leader = value; }
    }
    private uint _createtime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"createtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint createtime
    {
      get { return _createtime; }
      set { _createtime = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _member = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"member", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> member
    {
      get { return _member; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchTeamReq")]
  public partial class MatchTeamReq : global::ProtoBuf.IExtensible
  {
    public MatchTeamReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.MATCH_TEAM_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.MATCH_TEAM_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchTeamRet")]
  public partial class MatchTeamRet : global::ProtoBuf.IExtensible
  {
    public MatchTeamRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.MATCH_TEAM_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.MATCH_TEAM_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuitTeamReq")]
  public partial class QuitTeamReq : global::ProtoBuf.IExtensible
  {
    public QuitTeamReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.QUIT_TEAM_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.QUIT_TEAM_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _teamid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint teamid
    {
      get { return _teamid; }
      set { _teamid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuitTeamRet")]
  public partial class QuitTeamRet : global::ProtoBuf.IExtensible
  {
    public QuitTeamRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.QUIT_TEAM_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.QUIT_TEAM_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickOutTeamReq")]
  public partial class KickOutTeamReq : global::ProtoBuf.IExtensible
  {
    public KickOutTeamReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.KICK_OUT_TEAM_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.KICK_OUT_TEAM_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _roleid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickOutTeamRet")]
  public partial class KickOutTeamRet : global::ProtoBuf.IExtensible
  {
    public KickOutTeamRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.KICK_OUT_TEAM_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.KICK_OUT_TEAM_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartTeamFightReq")]
  public partial class StartTeamFightReq : global::ProtoBuf.IExtensible
  {
    public StartTeamFightReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.START_TEAM_FIGHT_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.START_TEAM_FIGHT_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartTeamFightRet")]
  public partial class StartTeamFightRet : global::ProtoBuf.IExtensible
  {
    public StartTeamFightRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.START_TEAM_FIGHT_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.START_TEAM_FIGHT_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamListReq")]
  public partial class TeamListReq : global::ProtoBuf.IExtensible
  {
    public TeamListReq() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.TEAM_LIST_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.TEAM_LIST_REQ)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamListRet")]
  public partial class TeamListRet : global::ProtoBuf.IExtensible
  {
    public TeamListRet() {}
    
    private Cmd.EProtoId _id = Cmd.EProtoId.TEAM_LIST_RET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EProtoId.TEAM_LIST_RET)]
    public Cmd.EProtoId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.TeamInfo> _list = new global::System.Collections.Generic.List<Cmd.TeamInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.TeamInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}