//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: zone.proto
namespace http
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Zone")]
  public partial class Zone : global::ProtoBuf.IExtensible
  {
    public Zone() {}
    
    private int _serv_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serv_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serv_id
    {
      get { return _serv_id; }
      set { _serv_id = value; }
    }
    private string _serv_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serv_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serv_name
    {
      get { return _serv_name; }
      set { _serv_name = value; }
    }
    private string _remote_ip;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"remote_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string remote_ip
    {
      get { return _remote_ip; }
      set { _remote_ip = value; }
    }
    private int _port;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _recommend_flag;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"recommend_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recommend_flag
    {
      get { return _recommend_flag; }
      set { _recommend_flag = value; }
    }
    private uint _publish_time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"publish_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint publish_time
    {
      get { return _publish_time; }
      set { _publish_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimpleZone")]
  public partial class SimpleZone : global::ProtoBuf.IExtensible
  {
    public SimpleZone() {}
    
    private int _serv_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serv_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serv_id
    {
      get { return _serv_id; }
      set { _serv_id = value; }
    }
    private string _serv_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serv_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serv_name
    {
      get { return _serv_name; }
      set { _serv_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetZoneList")]
  public partial class GetZoneList : global::ProtoBuf.IExtensible
  {
    public GetZoneList() {}
    
    private readonly global::System.Collections.Generic.List<http.Zone> _zone = new global::System.Collections.Generic.List<http.Zone>();
    [global::ProtoBuf.ProtoMember(1, Name=@"zone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<http.Zone> zone
    {
      get { return _zone; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetZoneInfo")]
  public partial class GetZoneInfo : global::ProtoBuf.IExtensible
  {
    public GetZoneInfo() {}
    
    private http.Zone _zone;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public http.Zone zone
    {
      get { return _zone; }
      set { _zone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRoleList")]
  public partial class GetRoleList : global::ProtoBuf.IExtensible
  {
    public GetRoleList() {}
    
    private readonly global::System.Collections.Generic.List<http.SimpleZone> _zone = new global::System.Collections.Generic.List<http.SimpleZone>();
    [global::ProtoBuf.ProtoMember(1, Name=@"zone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<http.SimpleZone> zone
    {
      get { return _zone; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}