//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NetBufferWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("NetBuffer");
		L.RegFunction("SendCmd", SendCmd);
		L.RegVar("s_recvProtoId", get_s_recvProtoId, set_s_recvProtoId);
		L.RegVar("s_recvBytes", get_s_recvBytes, set_s_recvBytes);
		L.RegVar("s_sendProtoId", get_s_sendProtoId, set_s_sendProtoId);
		L.RegVar("s_sendBytes", get_s_sendBytes, set_s_sendBytes);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendCmd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = NetBuffer.SendCmd();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_s_recvProtoId(IntPtr L)
	{
		LuaDLL.lua_pushinteger(L, NetBuffer.s_recvProtoId);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_s_recvBytes(IntPtr L)
	{
		ToLua.Push(L, NetBuffer.s_recvBytes);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_s_sendProtoId(IntPtr L)
	{
		LuaDLL.lua_pushinteger(L, NetBuffer.s_sendProtoId);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_s_sendBytes(IntPtr L)
	{
		ToLua.Push(L, NetBuffer.s_sendBytes);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_s_recvProtoId(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			NetBuffer.s_recvProtoId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_s_recvBytes(IntPtr L)
	{
		try
		{
			LuaByteBuffer arg0 = new LuaByteBuffer(ToLua.CheckByteBuffer(L, 2));
			NetBuffer.s_recvBytes = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_s_sendProtoId(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			NetBuffer.s_sendProtoId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_s_sendBytes(IntPtr L)
	{
		try
		{
			LuaByteBuffer arg0 = new LuaByteBuffer(ToLua.CheckByteBuffer(L, 2));
			NetBuffer.s_sendBytes = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

